(()=>{
'use strict';
if(window.ShooAntiCheat)return;
const LIMITS={maxDamage:5000,maxSpeed:36,minShotMs:45,maxHp:100000,maxCoinJump:50000,maxBossDamage:250000,strikesToBan:6};
const S={strikes:0,lastShot:0,lastPos:null,lastPosAt:0,lastCoins:null,lastHp:null,banned:false,admin:false,uid:null,db:null,auth:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ts=()=>window.firebase?.firestore?.FieldValue?.serverTimestamp?.()||new Date();
function toast(msg){let e=document.getElementById('antiCheatToast');if(!e){e=document.createElement('div');e.id='antiCheatToast';e.style.cssText='position:fixed;left:50%;top:18px;transform:translateX(-50%);z-index:999999;background:#260909;border:1px solid #ef4444;color:#fff;padding:12px 16px;border-radius:12px;font:700 13px system-ui;max-width:88vw;text-align:center';document.body.appendChild(e)}e.textContent=msg;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',3500)}
async function waitFirebase(){for(let i=0;i<80;i++){if(window.firebase?.apps?.length){S.auth=firebase.auth();S.db=firebase.firestore();if(S.auth.currentUser){S.uid=S.auth.currentUser.uid;return true}}await new Promise(r=>setTimeout(r,250))}return false}
async function log(type,detail,severity=1){console.warn('[ANTI-CHEAT]',type,detail);if(!S.db||!S.uid)return;try{await S.db.collection('cheatLogs').add({uid:S.uid,type,detail:String(detail).slice(0,400),severity,createdAt:ts(),userAgent:navigator.userAgent.slice(0,180),path:location.pathname})}catch{}}
async function strike(type,detail,severity=1){if(S.banned)return false;S.strikes+=severity;await log(type,detail,severity);toast(`不正な動作を検知しました (${S.strikes}/${LIMITS.strikesToBan})`);if(S.strikes>=LIMITS.strikesToBan)await autoBan(type);return false}
async function autoBan(reason){if(!S.db||!S.uid)return;S.banned=true;try{await S.db.collection('bans').doc(S.uid).set({uid:S.uid,active:true,reason:String(reason),strikes:S.strikes,createdAt:ts(),expiresAt:null},{merge:true})}catch{}blockGame('このアカウントは不正検知によりオンライン利用を停止されました。')}
function blockGame(message){document.querySelectorAll('button,input,textarea,select').forEach(x=>{if(!x.closest('#antiCheatAdmin'))x.disabled=true});let e=document.getElementById('antiCheatBlock');if(!e){e=document.createElement('div');e.id='antiCheatBlock';e.style.cssText='position:fixed;inset:0;z-index:999998;background:rgba(2,6,23,.97);display:flex;align-items:center;justify-content:center;padding:24px;color:white;font-family:system-ui';e.innerHTML=`<div style="max-width:560px;border:2px solid #ef4444;border-radius:18px;padding:24px;text-align:center"><h1 style="color:#f87171">ACCESS BLOCKED</h1><p id="antiCheatBlockText"></p></div>`;document.body.appendChild(e)}document.getElementById('antiCheatBlockText').textContent=message}
async function checkBan(){if(!S.db||!S.uid)return;const d=await S.db.collection('bans').doc(S.uid).get();if(d.exists&&d.data().active){S.banned=true;blockGame('このアカウントはBANされています。')}}
async function checkAdmin(){if(!S.db||!S.uid)return;const d=await S.db.collection('admins').doc(S.uid).get();S.admin=d.exists&&d.data().active===true;if(S.admin)installAdminButton()}
function finite(n){return typeof n==='number'&&Number.isFinite(n)}
function checkDamage(v,source='weapon'){if(!finite(v)||v<0||v>LIMITS.maxDamage)return strike('damage_limit',`${source}:${v}`,2);return true}
function checkBossDamage(v,bossId='boss'){if(!finite(v)||v<0||v>LIMITS.maxBossDamage)return strike('boss_damage_limit',`${bossId}:${v}`,3);return true}
function checkShot(){const n=performance.now(),dt=n-S.lastShot;S.lastShot=n;if(dt>0&&dt<LIMITS.minShotMs)return strike('fire_rate',`${Math.round(dt)}ms`,1);return true}
function checkMove(x,y){if(!finite(x)||!finite(y))return false;const n=performance.now();if(S.lastPos){const dt=(n-S.lastPosAt)/1000;if(dt>.01){const dist=Math.hypot(x-S.lastPos.x,y-S.lastPos.y),speed=dist/dt;if(speed>LIMITS.maxSpeed){S.lastPos={x,y};S.lastPosAt=n;return strike('move_speed',speed.toFixed(2),1)}}}S.lastPos={x,y};S.lastPosAt=n;return true}
function checkEconomy(coins,hp,maxHp){if(finite(coins)){if(coins<0||coins>1e9)strike('coins_invalid',coins,2);if(S.lastCoins!==null&&coins-S.lastCoins>LIMITS.maxCoinJump)strike('coins_jump',`${S.lastCoins}->${coins}`,2);S.lastCoins=coins}if(finite(hp)){const cap=finite(maxHp)?Math.min(maxHp,LIMITS.maxHp):LIMITS.maxHp;if(hp<0||hp>cap*1.05)strike('hp_invalid',`${hp}/${cap}`,2);S.lastHp=hp}}
function scanState(){const roots=[window.gameState,window.state,window.player,window.game,window.saveData].filter(Boolean);for(const r of roots){const coins=r.coins??r.coin??r.money;const hp=r.hp??r.health;const maxHp=r.maxHp??r.maxHealth;checkEconomy(Number(coins),Number(hp),Number(maxHp));const x=r.x??r.playerX,y=r.y??r.playerY;if(finite(x)&&finite(y))checkMove(x,y);const boss=r.boss??window.boss;if(boss){const bhp=Number(boss.hp??boss.health),bmax=Number(boss.maxHp??boss.maxHealth);if(finite(bhp)&&finite(bmax)&&(bhp<0||bhp>bmax*1.02))strike('boss_hp_invalid',`${bhp}/${bmax}`,3)}}}
function scanStorage(){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!/shoo|game|save|account/i.test(k))continue;try{const v=JSON.parse(localStorage.getItem(k));if(v&&typeof v==='object')checkEconomy(Number(v.coins??v.coin??v.money),Number(v.hp??v.health),Number(v.maxHp??v.maxHealth))}catch{}}}
function installAdminButton(){if(document.getElementById('antiCheatAdminButton'))return;const host=document.querySelector('.homeUtilityActions')||document.body;const b=document.createElement('button');b.id='antiCheatAdminButton';b.textContent='👑 管理者パネル';b.onclick=openAdmin;host.appendChild(b)}
async function openAdmin(){let e=document.getElementById('antiCheatAdmin');if(!e){e=document.createElement('div');e.id='antiCheatAdmin';e.className='screen';e.style.zIndex='999997';e.innerHTML='<div class="panel"><h1>管理者パネル</h1><button id="acReload">ログ更新</button><div id="acLogs" class="logbox"></div><input id="acBanUid" placeholder="UID"><input id="acBanReason" placeholder="理由"><button id="acBan">BANする</button><button id="acUnban">BAN解除</button><button class="back" id="acClose">閉じる</button></div>';document.body.appendChild(e);e.querySelector('#acReload').onclick=loadLogs;e.querySelector('#acBan').onclick=()=>adminBan(true);e.querySelector('#acUnban').onclick=()=>adminBan(false);e.querySelector('#acClose').onclick=()=>e.remove()}await loadLogs()}
async function loadLogs(){const box=document.getElementById('acLogs');if(!box||!S.db)return;box.textContent='読み込み中...';try{const s=await S.db.collection('cheatLogs').orderBy('createdAt','desc').limit(60).get();box.innerHTML=s.docs.map(d=>{const x=d.data();return `<div class="logitem"><b>${esc(x.type)}</b> / ${esc(x.uid)}<br>${esc(x.detail)}</div>`}).join('')||'ログなし'}catch(e){box.textContent=e.message}}
async function adminBan(active){if(!S.admin||!S.db)return;const uid=document.getElementById('acBanUid').value.trim();if(!uid)return;const reason=document.getElementById('acBanReason').value.trim()||'管理者操作';await S.db.collection('bans').doc(uid).set({uid,active,reason,updatedAt:ts(),by:S.uid},{merge:true});await log('admin_ban_change',`${uid}:${active}`,1);alert(active?'BANしました':'BAN解除しました')}
async function init(){if(!await waitFirebase())return;await checkBan();await checkAdmin();setInterval(scanState,700);setInterval(scanStorage,2500)}
window.ShooAntiCheat={checkDamage,checkBossDamage,checkShot,checkMove,checkEconomy,strike,log,get banned(){return S.banned},get admin(){return S.admin}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();