(()=>{
'use strict';
const VERSION='5.2.6';
// Bump UPDATE_ID whenever any app file is updated so every release is announced once per browser.
const UPDATE_ID='5.2.6-mobile-login-warp-r79';
const SEEN_KEY='shooking2_last_seen_update';
let stack=null,release=null;
const style=document.createElement('style');
style.textContent=`
#shooNoticeStack{position:fixed;right:max(14px,env(safe-area-inset-right));top:max(14px,env(safe-area-inset-top));z-index:2147483600;display:grid;gap:10px;width:min(390px,calc(100vw - 28px));pointer-events:none}.shooNotice{position:relative;display:grid;grid-template-columns:42px minmax(0,1fr) 28px;gap:10px;align-items:start;padding:13px 12px;border:1px solid rgba(103,232,249,.35);border-radius:14px;background:linear-gradient(145deg,rgba(7,18,38,.97),rgba(2,6,23,.98));box-shadow:0 18px 50px rgba(0,0,0,.5),inset 3px 0 0 #38bdf8;color:#e5f8ff;pointer-events:auto;overflow:hidden;animation:shooNoticeIn .28s cubic-bezier(.2,.8,.2,1)}.shooNotice::after{content:"";position:absolute;left:0;bottom:0;height:2px;width:100%;background:linear-gradient(90deg,#38bdf8,#8b5cf6,transparent);transform-origin:left;animation:shooNoticeLife var(--life,6s) linear forwards}.shooNotice.error{border-color:rgba(248,113,113,.42);box-shadow:0 18px 50px rgba(0,0,0,.5),inset 3px 0 0 #ef4444}.shooNotice.success{box-shadow:0 18px 50px rgba(0,0,0,.5),inset 3px 0 0 #22c55e}.shooNoticeIcon{width:42px;height:42px;display:grid;place-items:center;border:1px solid rgba(103,232,249,.24);border-radius:12px;background:rgba(56,189,248,.08);font-size:20px}.shooNoticeTitle{color:#67e8f9;font:900 10px/1.2 ui-monospace,monospace;letter-spacing:.14em}.shooNoticeText{margin-top:4px;color:#d4e4f3;font-size:12px;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}.shooNoticeClose{width:28px!important;min-height:28px!important;margin:0!important;padding:0!important;border:0!important;border-radius:8px!important;background:rgba(148,163,184,.1)!important;color:#94a3b8!important;font-size:16px!important}.shooNotice.out{animation:shooNoticeOut .2s ease forwards}
#shooReleaseNotice{position:fixed;right:max(18px,env(safe-area-inset-right));bottom:max(18px,env(safe-area-inset-bottom));z-index:2147483550;width:min(430px,calc(100vw - 28px));border:1px solid rgba(103,232,249,.42);border-radius:20px;background:linear-gradient(150deg,rgba(8,25,49,.98),rgba(2,6,23,.99));box-shadow:0 28px 90px rgba(0,0,0,.68),0 0 38px rgba(56,189,248,.16);color:#e8f7ff;overflow:hidden;animation:shooReleaseIn .38s cubic-bezier(.2,.8,.2,1)}#shooReleaseNotice::before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(120deg,transparent 0 44%,rgba(103,232,249,.06) 45%,transparent 46% 100%)}.shooReleaseHead{position:relative;display:flex;align-items:center;gap:12px;padding:16px 17px;border-bottom:1px solid rgba(103,232,249,.15);background:rgba(56,189,248,.055)}.shooReleaseBadge{display:grid;place-items:center;width:48px;height:48px;border:1px solid rgba(250,204,21,.4);border-radius:14px;background:rgba(250,204,21,.07);color:#fde047;font:1000 12px/1 ui-monospace,monospace;box-shadow:0 0 18px rgba(250,204,21,.09)}.shooReleaseTitle{font-size:18px;font-weight:1000;letter-spacing:.02em}.shooReleaseSub{margin-top:3px;color:#67e8f9;font:800 9px/1.2 ui-monospace,monospace;letter-spacing:.15em}.shooReleaseClose{margin-left:auto!important;width:34px!important;min-height:34px!important;padding:0!important;border:1px solid rgba(148,163,184,.16)!important;border-radius:10px!important;background:rgba(148,163,184,.08)!important;color:#cbd5e1!important;font-size:17px!important}.shooReleaseBody{position:relative;padding:15px 18px 17px}.shooReleaseLead{margin:0 0 11px;color:#dbeafe;font-size:12px;line-height:1.55}.shooReleaseList{display:grid;gap:7px;margin:0;padding:0;list-style:none}.shooReleaseList li{display:grid;grid-template-columns:20px 1fr;gap:8px;align-items:start;padding:8px 9px;border:1px solid rgba(148,163,184,.1);border-radius:10px;background:rgba(2,6,23,.38);color:#bcd0e3;font-size:11px;line-height:1.45}.shooReleaseList li::before{content:"✓";display:grid;place-items:center;width:18px;height:18px;border-radius:50%;background:rgba(34,197,94,.12);color:#4ade80;font-weight:1000}.shooReleaseFoot{display:flex;justify-content:space-between;align-items:center;margin-top:12px;color:#64748b;font:700 9px/1 ui-monospace,monospace;letter-spacing:.08em}.shooReleaseButton{width:auto!important;min-height:34px!important;margin:0!important;padding:0 12px!important;border:1px solid rgba(103,232,249,.25)!important;border-radius:9px!important;background:linear-gradient(90deg,#0891b2,#2563eb)!important;color:#fff!important;font-size:10px!important}
@keyframes shooNoticeIn{from{opacity:0;transform:translateX(24px) scale(.98)}to{opacity:1;transform:none}}@keyframes shooNoticeOut{to{opacity:0;transform:translateX(18px) scale(.98)}}@keyframes shooNoticeLife{from{transform:scaleX(1)}to{transform:scaleX(0)}}@keyframes shooReleaseIn{from{opacity:0;transform:translateY(24px) scale(.97)}to{opacity:1;transform:none}}
@media(max-width:600px),(pointer:coarse){#shooNoticeStack{left:10px;right:10px;top:max(10px,env(safe-area-inset-top));width:auto}.shooNotice{grid-template-columns:36px minmax(0,1fr) 28px;padding:11px 10px}.shooNoticeIcon{width:36px;height:36px;font-size:17px}#shooReleaseNotice{left:10px;right:10px;bottom:max(10px,env(safe-area-inset-bottom));width:auto}.shooReleaseHead{padding:13px}.shooReleaseBody{padding:13px}.shooReleaseBadge{width:42px;height:42px}}
@media(prefers-reduced-motion:reduce){.shooNotice,#shooReleaseNotice,.shooNotice::after{animation:none!important}}
`;
document.head.appendChild(style);
function ensureStack(){if(stack)return stack;stack=document.createElement('div');stack.id='shooNoticeStack';document.body.appendChild(stack);return stack}
function iconFor(type){return type==='error'?'⚠':type==='success'?'✓':'◆'}
function showNotice(input,options={}){const data=typeof input==='object'&&input?input:{message:String(input??'')};const message=String(data.message??data.text??input??'');const type=data.type||options.type||(/エラー|失敗|できません|無効|警告/i.test(message)?'error':'info');const title=data.title||options.title||(type==='error'?'SYSTEM WARNING':type==='success'?'MISSION UPDATE':'SYSTEM NOTICE');const duration=Math.max(2200,Number(data.duration||options.duration||6500));const card=document.createElement('div');card.className=`shooNotice ${type}`;card.style.setProperty('--life',`${duration}ms`);card.innerHTML=`<div class="shooNoticeIcon">${iconFor(type)}</div><div><div class="shooNoticeTitle"></div><div class="shooNoticeText"></div></div><button class="shooNoticeClose" type="button" aria-label="閉じる">×</button>`;card.querySelector('.shooNoticeTitle').textContent=title;card.querySelector('.shooNoticeText').textContent=message;const remove=()=>{if(!card.isConnected)return;card.classList.add('out');setTimeout(()=>card.remove(),210)};card.querySelector('button').onclick=remove;ensureStack().prepend(card);while(stack.children.length>4)stack.lastElementChild?.remove();if(duration>0)setTimeout(remove,duration);return card}
function closeRelease(markSeen=true){if(markSeen)try{localStorage.setItem(SEEN_KEY,UPDATE_ID)}catch{}release?.remove();release=null}
function showReleaseNotes(force=false){if(release)return release;if(!force){try{if(localStorage.getItem(SEEN_KEY)===UPDATE_ID)return null}catch{}}release=document.createElement('section');release.id='shooReleaseNotice';release.innerHTML=`<div class="shooReleaseHead"><div class="shooReleaseBadge">5.2.6</div><div><div class="shooReleaseTitle">SHOO KING II UPDATE</div><div class="shooReleaseSub">MOBILE WARP PARITY / R79</div></div><button class="shooReleaseClose" type="button" aria-label="閉じる">×</button></div><div class="shooReleaseBody"><p class="shooReleaseLead">スマホでもPCと同じログイン成功ワープが表示されるように調整しました。</p><ul class="shooReleaseList"><li>味方機・ワープ弾・転送ゲートをスマホ画面内へ最適配置</li><li>縦向き・横向き・iPhoneの安全領域に対応</li><li>Googleログインで画面が戻った後もワープ演出を再開</li><li>キーボードを閉じてから全画面演出とホーム移動を実行</li></ul><div class="shooReleaseFoot"><span>SHOO KING NETWORK // ${UPDATE_ID}</span><button class="shooReleaseButton" type="button">確認した</button></div></div>`;release.querySelector('.shooReleaseClose').onclick=()=>closeRelease(true);release.querySelector('.shooReleaseButton').onclick=()=>closeRelease(true);document.body.appendChild(release);return release}
function install(){ensureStack();const oldAlert=window.alert;window.__nativeAlert=oldAlert;window.alert=message=>{showNotice(String(message??''),{duration:7200});return undefined};window.showAppNotice=showNotice;window.showReleaseNotes=()=>showReleaseNotes(true);window.__shookingNoticeVersion=VERSION;window.__shookingUpdateId=UPDATE_ID;setTimeout(()=>showReleaseNotes(false),1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();