(()=>{
'use strict';
const $=id=>document.getElementById(id);
let ctx=null,timer=null,bindTimer=null;
const THEMES={normal:{title:'CAPSULE SYSTEM',className:'normal'},rare:{title:'GOLD SIGNAL',className:'gold'},summer:{title:'COOL SUMMER SIGNAL',className:'summer'},winter:{title:'HEAT WINTER SIGNAL',className:'winter'}};
function audio(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!ctx)ctx=new C();if(ctx.state==='suspended')ctx.resume().catch(()=>{});return ctx}
function tone(f,t,d,type='sine',g=.05,end=null){const c=audio();if(!c)return;const o=c.createOscillator(),a=c.createGain();o.type=type;o.frequency.setValueAtTime(f,c.currentTime+t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(20,end),c.currentTime+t+d);a.gain.setValueAtTime(.0001,c.currentTime+t);a.gain.exponentialRampToValueAtTime(g,c.currentTime+t+.01);a.gain.exponentialRampToValueAtTime(.0001,c.currentTime+t+d);o.connect(a).connect(c.destination);o.start(c.currentTime+t);o.stop(c.currentTime+t+d+.04)}
function noise(t,d,g=.03,f=900){const c=audio();if(!c)return;const b=c.createBuffer(1,Math.max(1,c.sampleRate*d|0),c.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=(Math.random()*2-1)*(1-i/x.length);const s=c.createBufferSource(),q=c.createBiquadFilter(),a=c.createGain();q.type='bandpass';q.frequency.value=f;q.Q.value=.7;a.gain.value=g;s.buffer=b;s.connect(q).connect(a).connect(c.destination);s.start(c.currentTime+t)}
function machineSound(kind){tone(62,0,.8,'sine',.13,36);for(let i=0;i<11;i++){const t=.1+i*.13,base=kind==='summer'?510:kind==='winter'?150:kind==='rare'?230:180;tone(base+i*24,t,.075,i%2?'square':'sawtooth',.026,base+i*38);noise(t,.04,.012,kind==='summer'?2300:kind==='winter'?520:1100)}tone(kind==='summer'?880:kind==='winter'?260:kind==='rare'?620:480,1.55,.3,'triangle',.08,kind==='winter'?420:1250);noise(1.82,.25,.08,460);tone(88,1.82,.5,'sine',.16,34)}
function revealSound(kind,legend){noise(0,.24,.1,kind==='summer'?2800:kind==='winter'?700:1500);tone(90,0,.5,'sine',.13,35);const notes=legend?[523,659,784,1047,1319,1568]:kind==='summer'?[659,784,988,1319,1568]:kind==='winter'?[220,277,330,440,554]:kind==='rare'?[440,554,659,880,1109]:[330,392,494,659];notes.forEach((n,i)=>tone(n,.08+i*.1,.34,i%2?'triangle':'sine',legend?.09:.065,n*1.02));if(legend){noise(.45,.8,.07,2600);tone(1760,.5,.8,'sine',.05,3200)}}
function installStyle(){let s=$('gachaUpgradeStyle');if(s)s.remove();s=document.createElement('style');s.id='gachaUpgradeStyle';s.textContent=`
#realGachaOverlay{overflow:hidden;background:radial-gradient(circle at 50% 35%,rgba(15,35,70,.96),rgba(0,3,12,.99))!important;perspective:1000px}
.gxScene{position:relative;width:min(620px,96vw);min-height:500px;display:flex;align-items:center;justify-content:center;flex-direction:column;isolation:isolate}
.gxGrid{position:absolute;inset:-20%;background:linear-gradient(rgba(56,189,248,.09) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.09) 1px,transparent 1px);background-size:34px 34px;transform:rotateX(68deg) translateY(30%);animation:gxGridMove 3s linear infinite;z-index:-4}
.gxAura{position:absolute;width:440px;height:440px;border-radius:50%;background:radial-gradient(circle,rgba(56,189,248,.28),transparent 66%);filter:blur(10px);animation:gxPulse 1s ease-in-out infinite alternate;z-index:-3}
.gxScene.gold .gxAura{background:radial-gradient(circle,rgba(250,204,21,.42),transparent 66%)}.gxScene.summer .gxAura{background:radial-gradient(circle,rgba(34,211,238,.46),transparent 66%)}.gxScene.winter .gxAura{background:radial-gradient(circle,rgba(249,115,22,.46),transparent 66%)}
.gxHud{position:absolute;top:12px;left:50%;transform:translateX(-50%);width:min(520px,90vw);display:flex;justify-content:space-between;gap:12px;font:900 12px/1.3 ui-monospace,monospace;letter-spacing:.14em;color:#bae6fd;text-shadow:0 0 12px #38bdf8}.gxHud span:last-child{color:#fff}
.gxMachine{position:relative;width:min(330px,72vw);height:330px;transform-style:preserve-3d;animation:gxMachineIn .7s cubic-bezier(.2,1.4,.35,1) both}
.gxGlass{position:absolute;left:50%;top:0;transform:translateX(-50%);width:265px;height:210px;border:5px solid rgba(255,255,255,.72);border-radius:50% 50% 28% 28%;background:radial-gradient(circle at 35% 22%,rgba(255,255,255,.5),rgba(56,189,248,.14) 35%,rgba(2,6,23,.76) 78%);box-shadow:inset 0 0 35px rgba(255,255,255,.16),0 0 40px rgba(56,189,248,.35);overflow:hidden}
.gxScene.gold .gxGlass{box-shadow:inset 0 0 35px rgba(255,255,255,.18),0 0 52px rgba(250,204,21,.55)}
.gxCapsules{position:absolute;inset:16px}.gxCapsules i{position:absolute;width:42px;height:42px;border-radius:50%;background:linear-gradient(#e0f2fe 0 48%,#2563eb 49% 100%);border:2px solid rgba(255,255,255,.8);box-shadow:0 0 9px rgba(125,211,252,.7);animation:gxMix .85s ease-in-out infinite alternate;animation-delay:var(--delay);left:var(--x);top:var(--y)}
.gxScene.gold .gxCapsules i:nth-child(3n){background:linear-gradient(#fff7ae 0 48%,#f59e0b 49% 100%)}.gxScene.summer .gxCapsules i{background:linear-gradient(#ecfeff 0 48%,#06b6d4 49% 100%)}.gxScene.winter .gxCapsules i{background:linear-gradient(#fff7ed 0 48%,#ea580c 49% 100%)}
.gxBase{position:absolute;left:50%;bottom:24px;transform:translateX(-50%);width:290px;height:120px;border-radius:26px 26px 34px 34px;background:linear-gradient(145deg,#334155,#0f172a 55%,#020617);border:3px solid #64748b;box-shadow:inset 0 0 30px rgba(255,255,255,.08),0 20px 40px rgba(0,0,0,.6)}
.gxCore{position:absolute;left:50%;top:31px;transform:translateX(-50%);width:104px;height:46px;border-radius:10px;background:#020617;border:2px solid #38bdf8;color:#7dd3fc;display:grid;place-items:center;font:900 11px ui-monospace,monospace;letter-spacing:.12em;box-shadow:0 0 18px rgba(56,189,248,.7);animation:gxCoreBlink .35s steps(2) infinite}
.gxLever{position:absolute;right:-30px;top:32px;width:20px;height:82px;background:linear-gradient(90deg,#475569,#cbd5e1,#334155);border-radius:10px;transform-origin:50% 8px;animation:gxLever 1.1s .35s cubic-bezier(.2,1.3,.3,1) both}.gxLever:after{content:'';position:absolute;left:-9px;bottom:-16px;width:38px;height:38px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fda4af,#dc2626 60%,#450a0a);box-shadow:0 0 16px #ef4444}
.gxStatus{margin-top:4px;font:1000 18px ui-monospace,monospace;letter-spacing:.18em;color:#e0f2fe;text-shadow:0 0 18px #38bdf8;animation:gxStatus .55s steps(2) infinite}
.gxWarning{position:absolute;inset:0;display:grid;place-items:center;font:1000 clamp(34px,9vw,72px) ui-monospace,monospace;letter-spacing:.14em;color:#fef08a;text-shadow:0 0 18px #facc15,0 0 45px #ea580c;opacity:0;pointer-events:none;animation:gxWarning 1.1s 1.25s ease both}
.gxDrop{position:absolute;left:50%;top:54%;width:112px;height:112px;border-radius:50%;transform:translate(-50%,-50%) scale(.2);background:linear-gradient(#e0f2fe 0 48%,#2563eb 49% 100%);border:4px solid #fff;box-shadow:0 0 40px #38bdf8;opacity:0;animation:gxDrop 1s 1.72s cubic-bezier(.18,1.3,.35,1) forwards;z-index:5}.gxScene.gold .gxDrop{background:linear-gradient(#fff7ae 0 48%,#f59e0b 49% 100%);box-shadow:0 0 55px #facc15}.gxScene.summer .gxDrop{background:linear-gradient(#ecfeff 0 48%,#06b6d4 49% 100%);box-shadow:0 0 55px #22d3ee}.gxScene.winter .gxDrop{background:linear-gradient(#fff7ed 0 48%,#ea580c 49% 100%);box-shadow:0 0 55px #fb923c}
.gxSkip{position:absolute;right:16px;bottom:14px;width:auto!important;padding:8px 14px!important;margin:0!important;font-size:12px!important;background:rgba(15,23,42,.78)!important;border:1px solid #64748b!important}
.gxResult{position:relative;width:min(560px,94vw);min-height:470px;display:flex;flex-direction:column;align-items:center;justify-content:center;animation:gxResultIn .45s ease-out both}.gxBurst{position:absolute;inset:0;pointer-events:none}.gxBurst i{position:absolute;left:50%;top:47%;width:8px;height:8px;border-radius:50%;background:#fff;box-shadow:0 0 14px currentColor;animation:gxBurst 1.35s ease-out both;transform:rotate(var(--a)) translateX(0)}
.gxHolo{position:relative;width:min(390px,86vw);padding:30px 22px;border-radius:28px;text-align:center;background:linear-gradient(135deg,rgba(255,255,255,.92),rgba(165,243,252,.82));color:#06111f;border:2px solid rgba(255,255,255,.95);box-shadow:0 0 60px rgba(56,189,248,.8);transform-style:preserve-3d;animation:gxHolo .8s cubic-bezier(.2,1.4,.35,1) both}.gxResult.gold .gxHolo{background:linear-gradient(135deg,#fff,#fde68a);box-shadow:0 0 75px rgba(250,204,21,.95)}.gxResult.summer .gxHolo{background:linear-gradient(135deg,#fff,#cffafe);box-shadow:0 0 75px rgba(34,211,238,.95)}.gxResult.winter .gxHolo{background:linear-gradient(135deg,#fff,#fed7aa);box-shadow:0 0 75px rgba(249,115,22,.95)}
.gxRarity{font:1000 13px ui-monospace,monospace;letter-spacing:.2em}.gxStars{font-size:24px;margin:8px 0;letter-spacing:.12em}.gxName{font-size:clamp(24px,7vw,38px);font-weight:1000;line-height:1.08}.gxDesc{font-size:15px;font-weight:900;margin-top:12px}.gxNew{display:inline-block;margin-top:12px;padding:5px 12px;border-radius:999px;background:#ef4444;color:#fff;font-weight:1000;animation:gxPulse .45s infinite alternate}.gxTake{width:min(330px,82vw);margin-top:20px}
.seasonGachaPanel{margin:14px 0;padding:14px;border:1px solid #38bdf8;border-radius:16px;background:rgba(2,20,40,.82)}.seasonGachaGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.seasonGachaButton.summer{background:linear-gradient(135deg,#0891b2,#2563eb)}.seasonGachaButton.winter{background:linear-gradient(135deg,#ea580c,#991b1b)}.seasonGachaButton.locked{filter:grayscale(.7);opacity:.62}
@keyframes gxMachineIn{from{opacity:0;transform:translateY(70px) rotateX(-18deg) scale(.7)}to{opacity:1;transform:none}}@keyframes gxGridMove{to{background-position:0 34px,34px 0}}@keyframes gxPulse{to{transform:scale(1.08);opacity:.75}}@keyframes gxMix{from{transform:translate(-14px,-8px) rotate(-18deg)}to{transform:translate(16px,12px) rotate(22deg)}}@keyframes gxLever{0%{transform:rotate(0)}55%{transform:rotate(115deg)}100%{transform:rotate(0)}}@keyframes gxCoreBlink{50%{filter:brightness(1.8)}}@keyframes gxStatus{50%{opacity:.5}}@keyframes gxWarning{0%,35%{opacity:0;transform:scale(1.35)}45%,70%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(.86)}}@keyframes gxDrop{0%{opacity:0;transform:translate(-50%,-180%) scale(.2) rotate(-180deg)}60%{opacity:1;transform:translate(-50%,35%) scale(1.12) rotate(18deg)}78%{transform:translate(-50%,10%) scale(.94) rotate(-8deg)}100%{opacity:1;transform:translate(-50%,0) scale(1) rotate(0)}}@keyframes gxResultIn{from{opacity:0;transform:scale(.75)}to{opacity:1;transform:scale(1)}}@keyframes gxHolo{from{opacity:0;transform:rotateX(70deg) scale(.4)}to{opacity:1;transform:rotateX(0) scale(1)}}@keyframes gxBurst{to{opacity:0;transform:rotate(var(--a)) translateX(var(--d)) scale(.1)}}
`;document.head.appendChild(s)}
function month(){return new Date().getMonth()+1}function active(kind){const m=month();return kind==='summer'?m>=6&&m<=8:m===12||m<=2}
function boost(k,v){if(typeof player!=='undefined')player[k]=(Number(player[k])||0)+v}
function remember(id,name){const key='shooking2_limited_items';let a=[];try{a=JSON.parse(localStorage.getItem(key)||'[]')}catch{}const isNew=!a.some(x=>x.id===id);if(isNew){a.push({id,name,obtainedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(a))}return isNew}
function reward(kind){const r=Math.random();if(kind==='summer'){if(r<.25){boost('fire',.45);return ['cool-lizard','すずしーれんしゃトカゲ','連射力 +45%・冷気弾を解放',false]}if(r<.48){boost('knockback',1.4);return ['giant-wind','巨大ノックバック風','敵を猛烈に吹き飛ばす風圧を解放',false]}if(r<.7){boost('engine',.35);return ['water-booster','ウォーターブースター','移動性能 +35%・水しぶき走行',false]}if(r<.9){boost('damage',.3);return ['ice-missile','かき氷ミサイル','攻撃力 +30%・冷却爆発',false]}boost('damage',.5);boost('fire',.5);boost('knockback',2);return ['summer-dragon','サマードラゴン','超激レア！攻撃・連射・ノックバック大強化',true]}
if(kind==='winter'){if(r<.25){boost('maxHp',55);player.hp=player.maxHp;return ['heater-armor','暖房装甲ヒーター','最大HP +55・凍結耐性',false]}if(r<.48){boost('damage',.4);return ['stove-cannon','石油ストーブ砲','攻撃力 +40%・熱風爆発',false]}if(r<.7){boost('fire',.38);return ['kotatsu-turret','こたつ連射タレット','連射力 +38%・自動援護',false]}if(r<.9){boost('engine',.32);return ['hot-air-engine','温風エンジン','エンジン +32%・熱気加速',false]}boost('damage',.55);boost('maxHp',100);player.hp=player.maxHp;return ['sun-furnace','太陽炉ヒーター','超激レア！攻撃 +55%・最大HP +100',true]}
if(kind==='rare'){if(r<.25){boost('damage',.35);return ['rare-core','レア攻撃コア','攻撃力 大アップ +35%',false]}if(r<.5){boost('maxHp',50);player.hp=player.maxHp;return ['gold-armor','黄金装甲','最大HP +50',false]}if(r<.75){boost('fire',.35);return ['rapid-core','高速連射機構','連射力 大アップ +35%',false]}if(r<.95){boost('engine',.4);return ['gold-engine','金色エンジン','エンジン 大強化 +40%',false]}player.coins+=1000;return ['jackpot','LEGEND JACKPOT','超大当たり！1000コイン獲得',true]}
if(r<.35){boost('damage',.12);return ['chip','攻撃チップ','攻撃力 +12%',false]}if(r<.65){boost('maxHp',15);player.hp=player.maxHp;return ['plate','装甲プレート','最大HP +15',false]}if(r<.88){boost('fire',.12);return ['module','連射モジュール','連射力 +12%',false]}boost('engine',.12);return ['engine','小型エンジン','エンジン +12%',false]}
function capsules(){return Array.from({length:16},(_,i)=>`<i style="--x:${8+(i*37)%78}%;--y:${8+(i*53)%72}%;--delay:-${(i%7)*.12}s"></i>`).join('')}
function scene(kind){const o=$('realGachaOverlay'),w=$('realGachaMachineWrap'),old=$('realGachaResult');if(!o)return;if(w)w.style.display='none';if(old)old.style.display='none';o.querySelector('.gxScene,.gxResult')?.remove();const t=THEMES[kind]||THEMES.normal,d=document.createElement('div');d.className=`gxScene ${t.className}`;d.innerHTML=`<div class="gxGrid"></div><div class="gxAura"></div><div class="gxHud"><span>SHOO KING II // GACHA</span><span>${t.title}</span></div><div class="gxMachine"><div class="gxGlass"><div class="gxCapsules">${capsules()}</div></div><div class="gxBase"><div class="gxCore">ANALYZING</div><div class="gxLever"></div></div></div><div class="gxStatus">CAPSULE MIXING...</div><div class="gxWarning">${kind==='normal'?'LOCK ON':'RARE SIGNAL'}</div><div class="gxDrop"></div><button class="gxSkip" type="button">SKIP</button>`;o.appendChild(d);d.querySelector('.gxSkip').addEventListener('click',()=>finish(kind));machineSound(kind)}
function finish(kind){clearTimeout(timer);const o=$('realGachaOverlay');if(!o||o.querySelector('.gxResult'))return;o.querySelector('.gxScene')?.remove();const [id,name,desc,legend]=reward(kind),isNew=remember(id,name),t=THEMES[kind]||THEMES.normal,d=document.createElement('div'),count=legend?54:34;d.className=`gxResult ${t.className}`;d.innerHTML=`<div class="gxAura"></div><div class="gxBurst">${Array.from({length:count},(_,i)=>`<i style="--a:${i*(360/count)}deg;--d:${110+Math.random()*190}px;animation-delay:${Math.random()*.25}s"></i>`).join('')}</div><div class="gxHolo"><div class="gxRarity">${legend?'ULTIMATE LEGEND':kind==='normal'?'ITEM ACQUIRED':'LIMITED / RARE'}</div><div class="gxStars">${legend?'★★★★★★':'★★★★★'}</div><div class="gxName"></div><div class="gxDesc"></div>${isNew?'<div class="gxNew">NEW! 図鑑登録</div>':''}</div><button class="gxTake" type="button">受け取る</button>`;d.querySelector('.gxName').textContent=name;d.querySelector('.gxDesc').textContent=desc;d.querySelector('.gxTake').addEventListener('click',close);o.appendChild(d);if(typeof saveData==='function')saveData();if(typeof checkAchievements==='function')checkAchievements();if(navigator.vibrate)navigator.vibrate(legend?[80,40,120,40,180]:[70,40,110]);revealSound(kind,legend)}
function start(kind='normal'){installStyle();if((kind==='summer'||kind==='winter')&&!active(kind)){if(typeof showToast==='function')showToast(kind==='summer'?'すずしーガチャは6〜8月限定です':'暖房ガチャは12〜2月限定です');return}const cost=kind==='normal'?80:kind==='rare'?250:300;if(typeof player==='undefined'||player.coins<cost){if(typeof showToast==='function')showToast('コインが足りません');return}player.coins-=cost;if(typeof saveData==='function')saveData();const o=$('realGachaOverlay');if(!o)return;o.style.display='flex';scene(kind);clearTimeout(timer);timer=setTimeout(()=>finish(kind),3000)}
function close(){clearTimeout(timer);const o=$('realGachaOverlay');o?.querySelector('.gxScene,.gxResult')?.remove();if(o)o.style.display='none';if(typeof updateStats==='function')updateStats()}
function panel(){const host=$('gachaScreen')?.querySelector('.panel')||document.querySelector('#gachaScreen .panel');if(!host||host.querySelector('.seasonGachaPanel'))return;const p=document.createElement('div');p.className='seasonGachaPanel';p.innerHTML=`<div style="font-weight:1000;margin-bottom:10px">期間限定ガチャ</div><div class="seasonGachaGrid"><button class="seasonGachaButton summer ${active('summer')?'':'locked'}">🧊 すずしーガチャ<br><small>300コイン</small></button><button class="seasonGachaButton winter ${active('winter')?'':'locked'}">🔥 暖房ガチャ<br><small>300コイン</small></button></div>`;p.querySelector('.summer').onclick=()=>start('summer');p.querySelector('.winter').onclick=()=>start('winter');host.appendChild(p)}
function bind(){window.startRealGacha=x=>start(x?'rare':'normal');window.normalGacha=()=>start('normal');window.rareGacha=()=>start('rare');window.summerGacha=()=>start('summer');window.winterGacha=()=>start('winter');window.closeRealGacha=close;document.querySelectorAll('button[onclick]').forEach(b=>{const c=b.getAttribute('onclick')||'';if(/normalGacha\s*\(/.test(c)){b.removeAttribute('onclick');if(!b.dataset.gx){b.onclick=()=>start('normal');b.dataset.gx='1'}}else if(/rareGacha\s*\(/.test(c)){b.removeAttribute('onclick');if(!b.dataset.gx){b.onclick=()=>start('rare');b.dataset.gx='1'}}});panel()}
installStyle();bind();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});bindTimer=setInterval(bind,900);setTimeout(()=>clearInterval(bindTimer),15000);window.ShooGachaUpgrade={start,close,version:'4'};
})();