(()=>{
'use strict';
const VERSION='password-change-v2-button-fix';
const CONFIG_KEY='shooking2_firebase_config';
const CURRENT_KEY='shooking2_current_account';
const SDK='10.12.5';
let authPromise=null;
let busy=false;

const style=document.createElement('style');
style.textContent=`
#shooPasswordChange{margin:14px 0;padding:16px;border:1px solid rgba(103,232,249,.3);border-radius:16px;background:linear-gradient(145deg,rgba(8,25,49,.82),rgba(2,6,23,.9));text-align:left}
#shooPasswordChange h2{margin:0 0 6px;color:#7df9ff;font-size:18px}.shooPasswordLead{margin:0 0 12px;color:#9fb4c9;font-size:12px;line-height:1.5}.shooPasswordGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.shooPasswordGrid .full{grid-column:1/-1}#shooPasswordChange label{display:block;color:#9fb4c9;font-size:10px;font-weight:900}#shooPasswordChange input{margin:5px 0 0!important}#shooChangePasswordButton{margin:10px 0 0!important;background:linear-gradient(90deg,#0891b2,#2563eb,#7c3aed)!important;touch-action:manipulation}#shooPasswordStatus{min-height:18px;margin-top:8px;color:#93c5fd;font-size:11px}@media(max-width:560px){.shooPasswordGrid{grid-template-columns:1fr}.shooPasswordGrid .full{grid-column:auto}}
`;
document.head.appendChild(style);

function account(){try{return JSON.parse(localStorage.getItem(CURRENT_KEY)||'null')}catch{return null}}
function config(){if(window.SHOO_KING_FIREBASE_CONFIG)return window.SHOO_KING_FIREBASE_CONFIG;try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'null')}catch{return null}}
function setStatus(text,error=false){const el=document.getElementById('shooPasswordStatus');if(el){el.textContent=text;el.style.color=error?'#fca5a5':'#93c5fd'}}
function notify(title,message,type='info'){if(typeof window.showAppNotice==='function')window.showAppNotice({title,message,type,duration:5600});else window.alert(message)}
function loadScript(src,id,ready){return new Promise((resolve,reject)=>{if(ready())return resolve();const old=document.getElementById(id);if(old){const start=Date.now();const timer=setInterval(()=>{if(ready()){clearInterval(timer);resolve()}else if(Date.now()-start>15000){clearInterval(timer);reject(new Error('Firebaseの読み込みがタイムアウトしました'))}},80);return}const script=document.createElement('script');script.id=id;script.src=src;script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error('Firebaseライブラリを読み込めませんでした'));document.head.appendChild(script)})}
async function getAuth(){if(authPromise)return authPromise;authPromise=(async()=>{const c=config();if(!c||!c.apiKey||!c.appId)throw new Error('Firebase設定が見つかりません');await loadScript(`https://www.gstatic.com/firebasejs/${SDK}/firebase-app-compat.js`,'firebaseAppSdk',()=>!!window.firebase?.initializeApp);await loadScript(`https://www.gstatic.com/firebasejs/${SDK}/firebase-auth-compat.js`,'firebaseAuthSdk',()=>!!window.firebase?.auth);const app=firebase.apps&&firebase.apps.length?firebase.app():firebase.initializeApp(c);return app.auth()})();try{return await authPromise}catch(error){authPromise=null;throw error}}
function readable(error){const code=String(error&&error.code||'');if(code==='auth/wrong-password'||code==='auth/invalid-credential')return '現在のパスワードが違います。';if(code==='auth/requires-recent-login')return '一度ログアウトして、もう一度ログインしてから変更してください。';if(code==='auth/weak-password')return '新しいパスワードは6文字以上にしてください。';if(code==='auth/network-request-failed')return '通信に失敗しました。';return error&&error.message||'パスワードを変更できませんでした。'}
async function changePassword(){if(busy)return;const acc=account();if(!acc){setStatus('ログインしてから変更してください。',true);notify('PASSWORD CHANGE','ログインしてから変更してください。','error');return}if(!/password/i.test(String(acc.provider||''))){setStatus('GoogleログインのパスワードはGoogle側で変更してください。',true);notify('PASSWORD CHANGE','GoogleログインのパスワードはGoogle側で変更してください。','error');return}const current=document.getElementById('shooCurrentPassword')?.value||'';const next=document.getElementById('shooNewPassword')?.value||'';const confirm=document.getElementById('shooConfirmPassword')?.value||'';try{if(!current)throw new Error('現在のパスワードを入力してください。');if(next.length<6)throw new Error('新しいパスワードは6文字以上にしてください。');if(next!==confirm)throw new Error('確認用パスワードが一致しません。');if(current===next)throw new Error('現在と違うパスワードにしてください。');busy=true;const button=document.getElementById('shooChangePasswordButton');if(button){button.disabled=true;button.textContent='変更中...'}setStatus('本人確認中...');const auth=await getAuth();let user=auth.currentUser;if(!user){await new Promise(resolve=>{const stop=auth.onAuthStateChanged(value=>{user=value;stop();resolve()},()=>resolve())})}if(!user||!user.email)throw new Error('ログイン情報を確認できません。');const credential=firebase.auth.EmailAuthProvider.credential(user.email,current);await user.reauthenticateWithCredential(credential);await user.updatePassword(next);['shooCurrentPassword','shooNewPassword','shooConfirmPassword'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});setStatus('パスワードを変更しました。');notify('PASSWORD UPDATED','パスワードを変更しました。','success')}catch(error){const msg=readable(error);setStatus(msg,true);notify('PASSWORD CHANGE FAILED',msg,'error')}finally{busy=false;const button=document.getElementById('shooChangePasswordButton');if(button){button.disabled=false;button.textContent='パスワードを変更'}}}
function createPanel(){const panel=document.createElement('section');panel.id='shooPasswordChange';panel.innerHTML=`<h2>パスワード変更</h2><p class="shooPasswordLead">現在のパスワードで本人確認してから変更します。</p><div class="shooPasswordGrid"><label class="full">現在のパスワード<input id="shooCurrentPassword" type="password" autocomplete="current-password"></label><label>新しいパスワード<input id="shooNewPassword" type="password" minlength="6" autocomplete="new-password"></label><label>新しいパスワード（確認）<input id="shooConfirmPassword" type="password" minlength="6" autocomplete="new-password"></label></div><button id="shooChangePasswordButton" type="button">パスワードを変更</button><div id="shooPasswordStatus" aria-live="polite"></div>`;return panel}
function refresh(){const panel=document.getElementById('shooPasswordChange');if(!panel)return;const acc=account();const lead=panel.querySelector('.shooPasswordLead');if(!acc)lead.textContent='ログインしてから変更できます。';else if(!/password/i.test(String(acc.provider||'')))lead.textContent='GoogleログインのパスワードはGoogle側で変更してください。';else lead.textContent='現在のパスワードで本人確認してから変更します。'}
function inject(){const settings=document.querySelector('#settings .panel');if(!settings)return;if(!document.getElementById('shooPasswordChange')){const panel=createPanel();const firebaseArea=document.getElementById('googleLoginSettings');const danger=settings.querySelector('.dangerBox');if(firebaseArea)firebaseArea.insertAdjacentElement('afterend',panel);else if(danger)settings.insertBefore(panel,danger);else settings.appendChild(panel)}refresh();window.__shookingPasswordChange=VERSION}
document.addEventListener('click',event=>{const button=event.target.closest('#shooChangePasswordButton');if(!button)return;event.preventDefault();event.stopPropagation();changePassword()},true);
document.addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target.closest('#shooPasswordChange')){event.preventDefault();changePassword()}},true);
function install(){inject();new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});setInterval(inject,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();