(()=>{
'use strict';
const VERSION='password-change-v1';
const CONFIG_KEY='shooking2_firebase_config';
const CURRENT_KEY='shooking2_current_account';
const SDK_VERSION='10.12.5';
let authPromise=null;

const style=document.createElement('style');
style.textContent=`
#shooPasswordChange{margin:14px 0;padding:16px;border:1px solid rgba(103,232,249,.3);border-radius:16px;background:linear-gradient(145deg,rgba(8,25,49,.82),rgba(2,6,23,.9));text-align:left;box-shadow:inset 0 0 24px rgba(56,189,248,.05)}
#shooPasswordChange h2{margin:0 0 6px;color:#7df9ff;font-size:18px}#shooPasswordChange .shooPasswordLead{margin:0 0 12px;color:#9fb4c9;font-size:12px;line-height:1.55}
.shooPasswordGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.shooPasswordGrid .full{grid-column:1/-1}
#shooPasswordChange label{display:block;color:#9fb4c9;font-size:10px;font-weight:900;letter-spacing:.08em}
#shooPasswordChange input{margin:5px 0 0!important}#shooPasswordChange button{margin:10px 0 0!important;background:linear-gradient(90deg,#0891b2,#2563eb,#7c3aed)!important}
#shooPasswordStatus{min-height:18px;margin-top:8px;color:#93c5fd;font-size:11px;line-height:1.45}.shooPasswordUnavailable{border-color:rgba(148,163,184,.2)!important;opacity:.72}
@media(max-width:560px){.shooPasswordGrid{grid-template-columns:1fr}.shooPasswordGrid .full{grid-column:auto}#shooPasswordChange{padding:12px}}
`;
document.head.appendChild(style);

function notice(title,message,type='info'){try{window.showAppNotice?.({title,message,type,duration:5600})}catch{}}
function account(){try{return JSON.parse(localStorage.getItem(CURRENT_KEY)||'null')}catch{return null}}
function config(){if(window.SHOO_KING_FIREBASE_CONFIG)return window.SHOO_KING_FIREBASE_CONFIG;try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'null')}catch{return null}}
function loadScript(src,id,ready){return new Promise((resolve,reject)=>{if(ready())return resolve();const old=document.getElementById(id);if(old){const started=Date.now(),timer=setInterval(()=>{if(ready()){clearInterval(timer);resolve()}else if(Date.now()-started>15000){clearInterval(timer);reject(new Error('Firebaseの読み込みがタイムアウトしました'))}},80);return}const script=document.createElement('script');script.id=id;script.src=src;script.async=true;script.onload=resolve;script.onerror=()=>reject(new Error('Firebaseライブラリを読み込めませんでした'));document.head.appendChild(script)})}
async function getAuth(){if(authPromise)return authPromise;authPromise=(async()=>{const c=config();if(!c?.apiKey||!c?.appId)throw new Error('Firebase設定が見つかりません');await loadScript(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-app-compat.js`,'firebaseAppSdk',()=>!!window.firebase?.initializeApp);await loadScript(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-auth-compat.js`,'firebaseAuthSdk',()=>!!window.firebase?.auth);const app=firebase.apps?.length?firebase.app():firebase.initializeApp(c);const auth=app.auth();await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);return auth})();try{return await authPromise}catch(error){authPromise=null;throw error}}
function setStatus(text,error=false){const el=document.getElementById('shooPasswordStatus');if(!el)return;el.textContent=text;el.style.color=error?'#fca5a5':'#93c5fd'}
function readable(error){const code=String(error?.code||'');if(code==='auth/wrong-password'||code==='auth/invalid-credential')return '現在のパスワードが違います。';if(code==='auth/requires-recent-login')return '安全のため再ログインが必要です。一度ログアウトしてログインし直してください。';if(code==='auth/weak-password')return '新しいパスワードは6文字以上にしてください。';if(code==='auth/network-request-failed')return '通信に失敗しました。接続を確認してください。';if(code==='auth/too-many-requests')return '試行回数が多すぎます。少し時間をおいてください。';return error?.message||'パスワードを変更できませんでした。'}
async function changePassword(){const button=document.getElementById('shooChangePasswordButton');const current=document.getElementById('shooCurrentPassword')?.value||'';const next=document.getElementById('shooNewPassword')?.value||'';const confirm=document.getElementById('shooConfirmPassword')?.value||'';try{if(!current)throw new Error('現在のパスワードを入力してください。');if(next.length<6)throw new Error('新しいパスワードは6文字以上にしてください。');if(next!==confirm)throw new Error('新しいパスワードが確認欄と一致しません。');if(current===next)throw new Error('現在と違うパスワードを入力してください。');button.disabled=true;setStatus('本人確認中...');const auth=await getAuth();let user=auth.currentUser;if(!user){await new Promise(resolve=>{const stop=auth.onAuthStateChanged(value=>{user=value;stop();resolve()},()=>resolve())})}if(!user)throw new Error('ログインしてから変更してください。');const hasPassword=user.providerData?.some(item=>item.providerId==='password');if(!hasPassword)throw new Error('GoogleログインのパスワードはGoogle側で変更してください。');const credential=firebase.auth.EmailAuthProvider.credential(user.email,current);await user.reauthenticateWithCredential(credential);setStatus('新しいパスワードを登録中...');await user.updatePassword(next);['shooCurrentPassword','shooNewPassword','shooConfirmPassword'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});setStatus('パスワードを変更しました。');notice('PASSWORD UPDATED','パスワードを安全に変更しました。','success')}catch(error){const message=readable(error);setStatus(message,true);notice('PASSWORD CHANGE FAILED',message,'error')}finally{if(button)button.disabled=false}}
function createPanel(){const panel=document.createElement('section');panel.id='shooPasswordChange';panel.innerHTML=`<h2>パスワード変更</h2><p class="shooPasswordLead">メールアドレスとパスワードでログインしている本人だけが変更できます。</p><div class="shooPasswordGrid"><label class="full">現在のパスワード<input id="shooCurrentPassword" type="password" autocomplete="current-password"></label><label>新しいパスワード<input id="shooNewPassword" type="password" minlength="6" autocomplete="new-password"></label><label>新しいパスワード（確認）<input id="shooConfirmPassword" type="password" minlength="6" autocomplete="new-password"></label></div><button id="shooChangePasswordButton" type="button">パスワードを変更</button><div id="shooPasswordStatus" aria-live="polite"></div>`;panel.querySelector('button').addEventListener('click',changePassword);panel.querySelectorAll('input').forEach(input=>input.addEventListener('keydown',event=>{if(event.key==='Enter')changePassword()}));return panel}
function refreshAvailability(){const panel=document.getElementById('shooPasswordChange');if(!panel)return;const acc=account();const passwordProvider=acc&&/password/i.test(String(acc.provider||''));panel.classList.toggle('shooPasswordUnavailable',!passwordProvider);const button=document.getElementById('shooChangePasswordButton');if(button)button.disabled=!passwordProvider;const lead=panel.querySelector('.shooPasswordLead');if(!acc)lead.textContent='ログインしてからパスワードを変更できます。';else if(!passwordProvider)lead.textContent='GoogleログインのパスワードはGoogleアカウント側で変更してください。';else lead.textContent='現在のパスワードで本人確認したあと、新しいパスワードへ変更します。'}
function inject(){const settings=document.querySelector('#settings .panel');if(!settings)return;if(!document.getElementById('shooPasswordChange')){const area=createPanel(),firebaseArea=document.getElementById('googleLoginSettings'),danger=settings.querySelector('.dangerBox');if(firebaseArea)firebaseArea.insertAdjacentElement('afterend',area);else if(danger)settings.insertBefore(area,danger);else settings.appendChild(area)}refreshAvailability();window.__shookingPasswordChange=VERSION}
function install(){inject();new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});setInterval(inject,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();