(()=>{'use strict';
const CURRENT='shooking2_current_account',PREFIX='sora_webstore_games_v4_',RECENT='sora_webstore_recent_v4_';
const builtins=[
{id:'shooking',name:'SHOO KING II',genre:'シューティング',description:'宇宙船、武器、機体を強化して進むブラウザシューティング。',url:new URL('./game?play=1&v=101&_pages=101&_stable=101',location.href).href,icon:'🚀',builtin:true},
{id:'guild',name:'Sora Guild',genre:'勉強',description:'勉強を楽しく続けるためのWebアプリ。',url:'https://sora-guild-app.vercel.app/',icon:'📚',builtin:true,study:true}
];
const $=id=>document.getElementById(id);let filter='',selected=null;
const read=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key)||'null');return value??fallback}catch{return fallback}};
const account=()=>read(CURRENT,null);const accountId=()=>{const a=account();return a?.uid||a?.email||a?.accountName||'guest'};
const customGames=()=>account()?read(PREFIX+accountId(),[]):[];const saveGames=list=>localStorage.setItem(PREFIX+accountId(),JSON.stringify(list));const allApps=()=>[...builtins,...customGames()];
function showToast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function showSheet(id){$(id).classList.add('open')}function hideSheet(id){$(id).classList.remove('open')}
function validUrl(value){try{const url=new URL(String(value).trim());return/^https?:$/.test(url.protocol)?url.href:''}catch{return''}}
function confirmOpen(app){return window.confirm('このWebページを信頼して開きますか？\n\nアプリ: '+(app.name||'Webアプリ')+'\n発行元: '+(app.builtin?'WebStore公式':'ユーザー登録')+'\n接続先: '+app.url+'\n\nOKを押した場合だけ開きます。')}
function remember(app){if(!account())return;const key=RECENT+accountId();let ids=read(key,[]);ids=[app.id,...ids.filter(id=>id!==app.id)].slice(0,6);localStorage.setItem(key,JSON.stringify(ids))}
function openApp(app,sameTab=false){if(!app?.url||!confirmOpen(app))return false;remember(app);renderRecent();if(sameTab){location.href=app.url;return true}const win=window.open(app.url,'_blank','noopener,noreferrer');if(!win)location.href=app.url;return true}
function makeRow(app){const row=document.createElement('article');row.className='app-row';const icon=document.createElement('div');icon.className='app-icon'+(app.study?' study':'');icon.textContent=app.icon||'🎮';const meta=document.createElement('div');meta.className='app-meta';const title=document.createElement('h3');title.textContent=app.name;const description=document.createElement('p');description.textContent=(app.genre||'ゲーム')+' · '+(app.description||'Webアプリ');meta.append(title,description);const open=document.createElement('button');open.className='open-button';open.textContent='開く';open.onclick=()=>openApp(app);const more=document.createElement('button');more.className='more-button';more.textContent='•••';more.onclick=()=>showMore(app);row.append(icon,meta,open,more);return row}
function renderList(id,items,emptyText='アプリがありません。'){const target=$(id);if(!items.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=emptyText;target.replaceChildren(empty);return}const box=document.createElement('div');box.className='app-list';items.forEach(app=>box.append(makeRow(app)));target.replaceChildren(box)}
function renderToday(){renderList('todayList',allApps().slice(0,6))}function renderGames(){renderList('gamesList',allApps().filter(app=>!filter||app.genre===filter))}
function renderLibrary(){const a=account();$('libraryMessage').textContent=a?'認証済み。追加したゲームはこのアカウント用に保存されます。':'認証するとゲームURLを登録できます。';renderList('libraryList',customGames(),a?'まだゲームが登録されていません。':'アカウント認証が必要です。');renderRecent()}
function renderRecent(){const map=new Map(allApps().map(app=>[app.id,app]));renderList('recentList',read(RECENT+accountId(),[]).map(id=>map.get(id)).filter(Boolean),'最近開いたアプリはありません。')}
function renderSearch(){const query=$('searchInput').value.trim().toLowerCase();const results=allApps().filter(app=>[app.name,app.genre,app.description,app.url].join(' ').toLowerCase().includes(query));$('searchCount').textContent=query?results.length+'件':'すべてのアプリ';renderList('searchList',results,'検索結果がありません。')}
function initial(){const a=account(),name=a?.accountName||a?.name||a?.email||'人';return String(name).trim().charAt(0).toUpperCase()||'人'}
function renderAccount(){const box=$('accountContent'),a=account();$('profileButton').textContent=initial();box.innerHTML='';if(a){box.innerHTML='<div class="account-card"><strong></strong><small></small><p>● 認証済み</p></div><button class="secondary wide" id="accountSettings">ゲーム側のアカウント設定を開く</button>';box.querySelector('strong').textContent=a.accountName||a.name||a.email||'Player';box.querySelector('small').textContent=a.email||a.provider||'SHOO KING II Account';$('accountSettings').onclick=()=>openApp(builtins[0],true)}else{box.innerHTML='<div class="account-card"><strong>WebStoreにサインイン</strong><p class="note">SHOO KING IIと同じアカウントを使います。</p></div><button class="primary wide" id="signInButton">SHOO KING IIでログイン</button><button class="secondary wide" id="checkLoginButton">ログイン状態を確認</button>';$('signInButton').onclick=()=>openApp(builtins[0],true);$('checkLoginButton').onclick=()=>{renderAll();showToast(account()?'認証を確認しました':'まだログインしていません')}}}
function requireAccount(){if(account())return true;renderAccount();showSheet('accountSheet');showToast('先にアカウント認証してください');return false}
function showMore(app){selected=app;$('moreTitle').textContent=app.name;$('moreDelete').style.display=app.builtin?'none':'block';showSheet('moreSheet')}
function switchView(name){document.querySelectorAll('.tabbar button').forEach(button=>button.classList.toggle('active',button.dataset.tab===name));document.querySelectorAll('.view').forEach(view=>view.classList.remove('active'));$(name+'View').classList.add('active');$('pageTitle').textContent={today:'おすすめ',games:'ゲーム',library:'ライブラリ',search:'検索'}[name];if(name==='library')renderLibrary();if(name==='search'){renderSearch();setTimeout(()=>$('searchInput').focus(),50)}window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderToday();renderGames();renderLibrary();renderSearch();renderAccount()}
$('dateLabel').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
document.querySelectorAll('[data-open-app]').forEach(button=>button.onclick=()=>openApp(builtins.find(app=>app.id===button.dataset.openApp)));
document.querySelectorAll('[data-switch]').forEach(button=>button.onclick=()=>switchView(button.dataset.switch));document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>switchView(button.dataset.tab));
document.querySelectorAll('[data-category]').forEach(button=>button.onclick=()=>{filter=button.dataset.category;document.querySelectorAll('[data-filter]').forEach(chip=>chip.classList.toggle('active',chip.dataset.filter===filter));renderGames();switchView('games')});document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(chip=>chip.classList.toggle('active',chip===button));renderGames()});
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>hideSheet(button.dataset.close));document.querySelectorAll('.sheet').forEach(sheet=>sheet.onclick=event=>{if(event.target===sheet)hideSheet(sheet.id)});
$('profileButton').onclick=()=>{renderAccount();showSheet('accountSheet')};$('addGameButton').onclick=()=>{if(requireAccount())showSheet('addSheet')};$('searchInput').oninput=renderSearch;
$('directOpenButton').onclick=()=>{const value=prompt('開きたいHTMLゲームURLを入力してください。','https://');if(value===null)return;const url=validUrl(value);if(!url){showToast('正しいURLを入力してください');return}openApp({id:'direct-'+Date.now(),name:'Direct URL',url,genre:'その他'})};
$('addForm').onsubmit=event=>{event.preventDefault();if(!requireAccount())return;const name=$('gameName').value.trim(),url=validUrl($('gameUrl').value);if(!name||!url){showToast('ゲーム名と正しいURLを入力してください');return}const list=customGames();list.unshift({id:'game-'+Date.now(),name,genre:$('gameGenre').value,description:$('gameDescription').value.trim(),url,icon:'🎮'});saveGames(list);event.target.reset();hideSheet('addSheet');renderAll();switchView('library');showToast('ライブラリへ追加しました')};
$('moreOpen').onclick=()=>selected&&openApp(selected);$('moreCopy').onclick=async()=>{if(!selected)return;try{await navigator.clipboard.writeText(selected.url);showToast('URLをコピーしました')}catch{showToast('コピーできませんでした')}};$('moreDelete').onclick=()=>{if(!selected||selected.builtin)return;if(!confirm('「'+selected.name+'」を削除しますか？'))return;saveGames(customGames().filter(app=>app.id!==selected.id));hideSheet('moreSheet');renderAll();showToast('削除しました')};
window.addEventListener('storage',event=>{if(event.key===CURRENT)renderAll()});window.addEventListener('pageshow',renderAll);renderAll();
})();