(()=>{
'use strict';
const $=id=>document.getElementById(id);
let audioCtx=null,revealTimer=null,bindTimer=null;
const THEMES={
 normal:{label:'CAPSULE SYSTEM',className:'normal',cost:80},
 rare:{label:'GOLD CAPSULE // LEGEND CHANCE',className:'gold',cost:250},
 summer:{label:'SUMMER LIMITED // COOL SIGNAL',className:'summer',cost:300},
 winter:{label:'WINTER LIMITED // HEAT SIGNAL',className:'winter',cost:300}
};
function audio(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audioCtx)audioCtx=new C();if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return audioCtx}
function tone(f,t,d,type='sine',g=.05,end=null){const c=audio();if(!c)return;const o=c.createOscillator(),a=c.createGain();o.type=type;o.frequency.setValueAtTime(f,c.currentTime+t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(20,end),c.currentTime+t+d);a.gain.setValueAtTime(.0001,c.currentTime+t);a.gain.exponentialRampToValueAtTime(g,c.currentTime+t+.01);a.gain.exponentialRampToValueAtTime(.0001,c.currentTime+t+d);o.connect(a).connect(c.destination);o.start(c.currentTime+t);o.stop(c.currentTime+t+d+.04)}
function noise(t,d,g=.03,f=900){const c=audio();if(!c)return;const b=c.createBuffer(1,Math.max(1,c.sampleRate*d|0),c.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=(Math.random()*2-1)*(1-i/x.length);const s=c.createBufferSource(),q=c.createBiquadFilter(),a=c.createGain();q.type='bandpass';q.frequency.value=f;q.Q.value=.8;a.gain.value=g;s.buffer=b;s.connect(q).connect(a).connect(c.destination);s.start(c.currentTime+t)}
function machineSound(kind){const base=kind==='summer'?520:kind==='winter'?145:kind==='rare'?235:175;tone(64,0,.7,'sine',.12,36);for(let i=0;i<12;i++){const t=.08+i*.12;tone(base+i*23,t,.07,i%2?'square':'sawtooth',.025,base+i*36);noise(t,.04,.012,kind==='summer'?2500:kind==='winter'?520:1200)}tone(kind==='summer'?980:kind==='winter'?280:kind==='rare'?720:500,1.52,.35,'triangle',.085,kind==='winter'?460:1500);noise(1.8,.25,.075,480);tone(86,1.8,.5,'sine',.15,34)}
function revealSound(kind,legend){noise(0,.24,.1,kind==='summer'?2800:kind==='winter'?700:1600);tone(92,0,.5,'sine',.13,35);const notes=legend?[523,659,784,1047,1319,1568]:kind==='summer'?[659,784,988,1319,1568]:kind==='winter'?[220,277,330,440,554]:kind==='rare'?[440,554,659,880,1109]:[330,392,494,659];notes.forEach((n,i)=>tone(n,.08+i*.1,.34,i%2?'triangle':'sine',legend?.09:.065,n*1.02));if(kind==='rare'||legend){noise(.45,.8,.07,2600);tone(1760,.5,.8,'sine',.05,3200)}}
function month(){return new Date().getMonth()+1}
function active(kind){const m=month();return kind==='summer'?(m>=6&&m<=8):(m===12||m<=2)}
function boost(k,v){if(typeof player==='undefined')return;player[k]=(Number(player[k])||0)+v}
function remember(id,name){const key='shooking2_limited_items';let a=[];try{a=JSON.parse(localStorage.getItem(key)||'[]')}catch{}const isNew=!a.some(x=>x.id===id);if(isNew){a.push({id,name,obtainedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(a))}return isNew}
function installStyle(){let s=$('gachaUpgradeStyle');if(s)s.remove();s=document.createElement('style');s.id='gachaUpgradeStyle';s.textContent=`
#realGachaOverlay{overflow:hidden!important;background:radial-gradient(circle at 50% 30%,rgba(19,38,75,.97),rgba(1,3,12,.995))!important;perspective:1000px}
.gxScene{position:relative;width:min(640px,96vw);min-height:510px;display:flex;align-items:center;justify-content:center;flex-direction:column;isolation:isolate}
.gxGrid{position:absolute;inset:-25%;background:linear-gradient(rgba(56,189,248,.09) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.09) 1px,transparent 1px);background-size:34px 34px;transform:rotateX(68deg) translateY(30%);animation:gxGrid 3s linear infinite;z-index:-5}
.gxAura{position:absolute;width:470px;height:470px;border-radius:50%;background:radial-gradient(circle,rgba(56,189,248,.3),transparent 66%);filter:blur(10px);animation:gxPulse 1s ease-in-out infinite alternate;z-index:-4}
.gxScene.gold .gxAura{background:radial-gradient(circle,rgba(255,215,0,.62),rgba(245,158,11,.2) 44%,transparent 68%);filter:blur(7px)}
.gxScene.summer .gxAura{background:radial-gradient(circle,rgba(34,211,238,.55),transparent 68%)}
.gxScene.winter .gxAura{background:radial-gradient(circle,rgba(249,115,22,.55),transparent 68%)}
.gxHud{position:absolute;top:10px;left:50%;transform:translateX(-50%);width:min(540px,92vw);display:flex;justify-content:space-between;gap:10px;font:1000 12px ui-monospace,monospace;letter-spacing:.13em;color:#bae6fd;text-shadow:0 0 14px #38bdf8}
.gxScene.gold .gxHud{color:#fff7ae;text-shadow:0 0 14px #facc15}.gxScene.summer .gxHud{color:#cffafe}.gxScene.winter .gxHud{color:#ffedd5}
.gxLimitedBadge{position:absolute;top:45px;left:50%;transform:translateX(-50%);padding:7px 16px;border-radius:999px;font:1000 12px ui-monospace,monospace;letter-spacing:.16em;background:rgba(2,6,23,.82);border:1px solid currentColor;box-shadow:0 0 18px currentColor}
.gxScene.gold .gxLimitedBadge{color:#fde047}.gxScene.summer .gxLimitedBadge{color:#67e8f9}.gxScene.winter .gxLimitedBadge{color:#fb923c}
.gxMachine{position:relative;width:min(350px,76vw);height:350px;transform-style:preserve-3d;animation:gxMachineIn .7s cubic-bezier(.2,1.4,.35,1) both}
.gxGlass{position:absolute;left:50%;top:0;transform:translateX(-50%);width:274px;height:214px;border:5px solid rgba(255,255,255,.75);border-radius:50% 50% 28% 28%;background:radial-gradient(circle at 35% 20%,rgba(255,255,255,.52),rgba(56,189,248,.13) 35%,rgba(2,6,23,.78) 79%);box-shadow:inset 0 0 38px rgba(255,255,255,.15),0 0 42px rgba(56,189,248,.4);overflow:hidden}
.gxScene.gold .gxGlass{border-color:#fde68a;background:radial-gradient(circle at 35% 20%,rgba(255,255,255,.7),rgba(250,204,21,.22) 38%,rgba(60,35,0,.82) 80%);box-shadow:inset 0 0 42px rgba(255,255,255,.24),0 0 30px #facc15,0 0 76px rgba(245,158,11,.9)}
.gxScene.summer .gxGlass{box-shadow:inset 0 0 38px rgba(255,255,255,.2),0 0 58px rgba(34,211,238,.75)}
.gxScene.winter .gxGlass{box-shadow:inset 0 0 38px rgba(255,255,255,.18),0 0 58px rgba(249,115,22,.75)}
.gxCapsules{position:absolute;inset:14px}.gxCapsules i{position:absolute;width:42px;height:42px;border-radius:50%;background:linear-gradient(#e0f2fe 0 48%,#2563eb 49% 100%);border:2px solid rgba(255,255,255,.82);box-shadow:0 0 10px rgba(125,211,252,.8);animation:gxMix .8s ease-in-out infinite alternate;animation-delay:var(--delay);left:var(--x);top:var(--y)}
.gxScene.gold .gxCapsules i{background:linear-gradient(#fffbd1 0 48%,#d97706 49% 100%);border-color:#fff7ae;box-shadow:0 0 16px #facc15}.gxScene.gold .gxCapsules i:nth-child(3n){background:linear-gradient(#fff 0 48%,#facc15 49% 100%)}
.gxScene.summer .gxCapsules i{background:linear-gradient(#ecfeff 0 48%,#06b6d4 49% 100%)}.gxScene.winter .gxCapsules i{background:linear-gradient(#fff7ed 0 48%,#ea580c 49% 100%)}
.gxBase{position:absolute;left:50%;bottom:22px;transform:translateX(-50%);width:305px;height:126px;border-radius:26px 26px 36px 36px;background:linear-gradient(145deg,#334155,#0f172a 55%,#020617);border:3px solid #64748b;box-shadow:inset 0 0 30px rgba(255,255,255,.08),0 22px 44px rgba(0,0,0,.62)}
.gxScene.gold .gxBase{background:linear-gradient(145deg,#fff3a3,#d97706 42%,#78350f);border-color:#fde68a;box-shadow:inset 0 0 35px rgba(255,255,255,.38),0 0 34px #facc15,0 22px 44px rgba(0,0,0,.7)}
.gxScene.summer .gxBase{background:linear-gradient(145deg,#67e8f9,#0369a1 55%,#082f49);border-color:#a5f3fc}.gxScene.winter .gxBase{background:linear-gradient(145deg,#fdba74,#c2410c 55%,#431407);border-color:#fed7aa}
.gxCore{position:absolute;left:50%;top:34px;transform:translateX(-50%);width:118px;height:48px;border-radius:10px;background:#020617;border:2px solid #38bdf8;color:#7dd3fc;display:grid;place-items:center;font:1000 11px ui-monospace,monospace;letter-spacing:.1em;box-shadow:0 0 18px rgba(56,189,248,.7);animation:gxBlink .35s steps(2) infinite}
.gxScene.gold .gxCore{border-color:#fde047;color:#fff7ae;box-shadow:0 0 24px #facc15}.gxScene.summer .gxCore{border-color:#67e8f9;color:#cffafe}.gxScene.winter .gxCore{border-color:#fb923c;color:#ffedd5}
.gxLever{position:absolute;right:-30px;top:34px;width:20px;height:84px;background:linear-gradient(90deg,#475569,#e2e8f0,#334155);border-radius:10px;transform-origin:50% 8px;animation:gxLever 1.1s .32s cubic-bezier(.2,1.3,.3,1) both}.gxLever:after{content:'';position:absolute;left:-9px;bottom:-16px;width:38px;height:38px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fda4af,#dc2626 60%,#450a0a);box-shadow:0 0 16px #ef4444}
.gxScene.gold .gxLever:after{background:radial-gradient(circle at 35% 30%,#fff7ae,#f59e0b 60%,#78350f);box-shadow:0 0 22px #facc15}
.gxStatus{margin-top:2px;font:1000 18px ui-monospace,monospace;letter-spacing:.17em;color:#e0f2fe;text-shadow:0 0 18px #38bdf8;animation:gxBlink .55s steps(2) infinite}.gxScene.gold .gxStatus{color:#fff7ae;text-shadow:0 0 22px #facc15}.gxScene.summer .gxStatus{color:#cffafe}.gxScene.winter .gxStatus{color:#ffedd5}
.gxWarning{position:absolute;inset:0;display:grid;place-items:center;font:1000 clamp(34px,9vw,72px) ui-monospace,monospace;letter-spacing:.14em;color:#fef08a;text-shadow:0 0 18px #facc15,0 0 45px #ea580c;opacity:0;pointer-events:none;animation:gxWarning 1.1s 1.18s ease both}.gxScene.summer .gxWarning{color:#cffafe;text-shadow:0 0 20px #22d3ee}.gxScene.winter .gxWarning{color:#ffedd5;text-shadow:0 0 20px #f97316}
.gxDrop{position:absolute;left:50%;top:54%;width:116px;height:116px;border-radius:50%;transform:translate(-50%,-50%) scale(.2);background:linear-gradient(#e0f2fe 0 48%,#2563eb 49% 100%);border:4px solid #fff;box-shadow:0 0 42px #38bdf8;opacity:0;animation:gxDrop 1s 1.68s cubic-bezier(.18,1.3,.35,1) forwards;z-index:5}.gxScene.gold .gxDrop{background:linear-gradient(#fffbd1 0 48%,#d97706 49% 100%);border-color:#fff7ae;box-shadow:0 0 28px #fff,0 0 64px #facc15,0 0 100px #f59e0b}.gxScene.summer .gxDrop{background:linear-gradient(#ecfeff 0 48%,#06b6d4 49% 100%);box-shadow:0 0 60px #22d3ee}.gxScene.winter .gxDrop{background:linear-gradient(#fff7ed 0 48%,#ea580c 49% 100%);box-shadow:0 0 60px #fb923c}
.gxSkip{position:absolute;right:16px;bottom:14px;width:auto!important;padding:8px 14px!important;margin:0!important;font-size:12px!important;background:rgba(15,23,42,.8)!important;border:1px solid #64748b!important}
.gxResult{position:relative;width:min(570px,94vw);min-height:480px;display:flex;flex-direction:column;align-items:center;justify-content:center;animation:gxResultIn .45s ease-out both}.gxBurst{position:absolute;inset:0;pointer-events:none}.gxBurst i{position:absolute;left:50%;top:47%;width:8px;height:8px;border-radius:50%;background:#fff;box-shadow:0 0 14px currentColor;animation:gxBurst 1.35s ease-out both;transform:rotate(var(--a)) translateX(0)}
.gxHolo{position:relative;width:min(400px,86vw);padding:32px 22px;border-radius:28px;text-align:center;background:linear-gradient(135deg,rgba(255,255,255,.94),rgba(165,243,252,.84));color:#06111f;border:2px solid rgba(255,255,255,.96);box-shadow:0 0 60px rgba(56,189,248,.84);animation:gxHolo .8s cubic-bezier(.2,1.4,.35,1) both}.gxResult.gold .gxHolo{background:linear-gradient(135deg,#fffef2,#fde68a 50%,#f59e0b);border-color:#fff7ae;box-shadow:0 0 30px #fff,0 0 80px #facc15,0 0 120px rgba(245,158,11,.85)}.gxResult.summer .gxHolo{background:linear-gradient(135deg,#fff,#cffafe);box-shadow:0 0 80px rgba(34,211,238,.96)}.gxResult.winter .gxHolo{background:linear-gradient(135deg,#fff,#fed7aa);box-shadow:0 0 80px rgba(249,115,22,.96)}
.gxRarity{font:1000 13px ui-monospace,monospace;letter-spacing:.2em}.gxStars{font-size:25px;margin:8px 0;letter-spacing:.12em}.gxName{font-size:clamp(24px,7vw,38px);font-weight:1000;line-height:1.08}.gxDesc{font-size:15px;font-weight:900;margin-top:12px}.gxNew{display:inline-block;margin-top:12px;padding:5px 12px;border-radius:999px;background:#ef4444;color:#fff;font-weight:1000;animation:gxPulse .45s infinite alternate}.gxTake{width:min(330px,82vw);margin-top:20px}
.seasonGachaPanel{margin:14px 0;padding:14px;border:1px solid #38bdf8;border-radius:16px;background:rgba(2,20,40,.88)}.seasonGachaTitle{font-weight:1000;font-size:18px;margin-bottom:10px}.seasonGachaGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.seasonGachaButton{min-height:74px;font-weight:1000}.seasonGachaButton.summer{background:linear-gradient(135deg,#06b6d4,#1d4ed8)!important}.seasonGachaButton.winter{background:linear-gradient(135deg,#f97316,#991b1b)!important}.seasonGachaButton.locked{filter:grayscale(.7);opacity:.62}.seasonGachaNote{font-size:12px;opacity:.82;margin-top:9px}
@keyframes gxMachineIn{from{opacity:0;transform:translateY(70px) rotateX(-18deg) scale(.7)}to{opacity:1;transform:none}}@keyframes gxGrid{to{background-position:0 34px,34px 0}}@keyframes gxPulse{to{transform:scale(1.08);opacity:.78}}@keyframes gxMix{from{transform:translate(-14px,-8px) rotate(-18deg)}to{transform:translate(16px,12px) rotate(22deg)}}@keyframes gxLever{0%{transform:rotate(0)}55%{transform:rotate(115deg)}100%{transform:rotate(0)}}@keyframes gxBlink{50%{filter:brightness(1.8);opacity:.58}}@keyframes gxWarning{0%,35%{opacity:0;transform:scale(1.35)}45%,70%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(.86)}}@keyframes gxDrop{0%{opacity:0;transform:translate(-50%,-180%) scale(.2) rotate(-180deg)}60%{opacity:1;transform:translate(-50%,35%) scale(1.12) rotate(18deg)}78%{transform:translate(-50%,10%) scale(.94) rotate(-8deg)}100%{opacity:1;transform:translate(-50%,0) scale(1) rotate(0)}}@keyframes gxResultIn{from{opacity:0;transform:scale(.75)}to{opacity:1;transform:scale(1)}}@keyframes gxHolo{from{opacity:0;transform:rotateX(70deg) scale(.4)}to{opacity:1;transform:rotateX(0) scale(1)}}@keyframes gxBurst{to{opacity:0;transform:rotate(var(--a)) translateX(var(--d)) scale(.1)}}
`;document.head.appendChild(s)}
function reward(kind){const r=Math.random();if(kind==='summer'){if(r<.25){boost('fire',.45);return ['cool-lizard','すずしーれんしゃトカゲ','連射力 +45%・冷気弾を解放',false]}if(r<.48){boost('knockback',1.4);return ['giant-wind','巨大ノックバック風','敵を猛烈に吹き飛ばす風圧を解放',false]}if(r<.68){boost('engine',.35);return ['water-booster','ウォーターブースター','移動性能 +35%・水しぶき走行',false]}if(r<.86){boost('damage',.3);return ['ice-missile','かき氷ミサイル','攻撃力 +30%・冷却爆発',false]}if(r<.97){boost('maxHp',60);player.hp=player.maxHp;return ['penguin-drone','ペンギンドローン','最大HP +60・援護ドローン獲得',true]}boost('damage',.5);boost('fire',.5);boost('knockback',2);return ['summer-dragon','サマードラゴン','超激レア！攻撃・連射・ノックバック大強化',true]}
if(kind==='winter'){if(r<.25){boost('maxHp',55);player.hp=player.maxHp;return ['heater-armor','暖房装甲ヒーター','最大HP +55・凍結耐性',false]}if(r<.48){boost('damage',.4);return ['stove-cannon','石油ストーブ砲','攻撃力 +40%・熱風爆発',false]}if(r<.68){boost('fire',.38);return ['kotatsu-turret','こたつ連射タレット','連射力 +38%・自動援護',false]}if(r<.86){boost('engine',.32);return ['hot-air-engine','温風エンジン','エンジン +32%・熱気加速',false]}if(r<.97){boost('maxHp',80);player.hp=player.maxHp;return ['floor-heating','床暖フィールド','最大HP +80・回復床を解放',true]}boost('damage',.55);boost('maxHp',100);player.hp=player.maxHp;return ['sun-furnace','太陽炉ヒーター','超激レア！攻撃 +55%・最大HP +100',true]}
if(kind==='rare'){if(r<.28){boost('damage',.35);return ['rare-attack','レア攻撃コア','攻撃力 大アップ +35%',false]}if(r<.52){boost('maxHp',50);player.hp=player.maxHp;return ['gold-armor','黄金装甲','最大HP +50',false]}if(r<.76){boost('fire',.35);return ['rapid-fire','高速連射機構','連射力 大アップ +35%',false]}if(r<.94){boost('engine',.4);return ['gold-engine','金色エンジン','エンジン 大強化 +40%',false]}player.coins+=1000;return ['legend-jackpot','LEGEND JACKPOT','超大当たり！1000コイン獲得',true]}
if(r<.35){boost('damage',.12);return ['attack-chip','攻撃チップ','攻撃力 +12%',false]}if(r<.65){boost('maxHp',15);player.hp=player.maxHp;return ['armor-plate','装甲プレート','最大HP +15',false]}if(r<.88){boost('fire',.12);return ['fire-module','連射モジュール','連射力 +12%',false]}boost('engine',.12);return ['small-engine','小型エンジン','エンジン +12%',false]}
function capsules(){return Array.from({length:18},(_,i)=>`<i style="--x:${8+Math.random()*78}%;--y:${10+Math.random()*68}%;--delay:${-Math.random().toFixed(2)}s"></i>`).join('')}
function showMachine(kind){const o=$('realGachaOverlay');if(!o)return;const t=THEMES[kind];o.querySelector('.gxScene,.gxResult')?.remove();const old=$('realGachaMachineWrap'),res=$('realGachaResult');if(old)old.style.display='none';if(res)res.style.display='none';const scene=document.createElement('div');scene.className=`gxScene ${t.className}`;scene.innerHTML=`<div class="gxGrid"></div><div class="gxAura"></div><div class="gxHud"><span>${t.label}</span><span>${t.cost} COINS</span></div>${kind!=='normal'?`<div class="gxLimitedBadge">${kind==='rare'?'★ GOLD RARE ★':kind==='summer'?'🌊 SUMMER LIMITED':'🔥 WINTER LIMITED'}</div>`:''}<div class="gxMachine"><div class="gxGlass"><div class="gxCapsules">${capsules()}</div></div><div class="gxBase"><div class="gxCore">${kind==='rare'?'GOLD MODE':kind==='summer'?'COOL MODE':kind==='winter'?'HEAT MODE':'SYSTEM ON'}</div><div class="gxLever"></div></div></div><div class="gxStatus">MIXING CAPSULES...</div><div class="gxWarning">${kind==='rare'?'GOLD SIGNAL':kind==='summer'?'COOL SIGNAL':kind==='winter'?'HEAT SIGNAL':'CAPSULE DROP'}</div><div class="gxDrop"></div><button class="gxSkip" type="button">SKIP</button>`;scene.querySelector('.gxSkip').addEventListener('click',()=>finish(kind,true));o.appendChild(scene)}
function showResult(kind,id,name,desc,legend){const o=$('realGachaOverlay');if(!o)return;o.querySelector('.gxScene,.gxResult')?.remove();const isNew=remember(id,name),t=THEMES[kind],count=legend?42:kind==='rare'?34:28;const p=Array.from({length:count},(_,i)=>`<i style="--a:${i*360/count}deg;--d:${120+Math.random()*180}px;animation-delay:${Math.random()*.18}s"></i>`).join('');const r=document.createElement('div');r.className=`gxResult ${t.className}`;r.innerHTML=`<div class="gxAura"></div><div class="gxBurst">${p}</div><div class="gxHolo"><div class="gxRarity">${legend?'ULTIMATE LEGEND':kind==='rare'?'GOLD RARE':kind==='summer'?'SUMMER LIMITED':kind==='winter'?'WINTER LIMITED':'ITEM GET'}</div><div class="gxStars">${legend?'★★★★★★':kind==='normal'?'★★★':'★★★★★'}</div><div class="gxName"></div><div class="gxDesc"></div>${isNew?'<div class="gxNew">NEW! 図鑑登録</div>':''}</div><button class="gxTake" type="button">受け取る</button>`;r.querySelector('.gxName').textContent=name;r.querySelector('.gxDesc').textContent=desc;r.querySelector('.gxTake').addEventListener('click',close);o.appendChild(r);revealSound(kind,legend);if(legend&&navigator.vibrate)navigator.vibrate([120,60,180,60,260])}
let pending=null;
function finish(kind){clearTimeout(revealTimer);if(!pending||pending.kind!==kind)return;const [id,name,desc,legend]=pending.reward;pending=null;if(typeof saveData==='function')saveData();if(typeof checkAchievements==='function')checkAchievements();const out=$('gachaResult');if(out)out.textContent=`${name}：${desc}`;showResult(kind,id,name,desc,legend)}
function start(kind){installStyle();if((kind==='summer'||kind==='winter')&&!active(kind)){const msg=kind==='summer'?'夏限定ガチャは6〜8月開催です':'冬限定ガチャは12〜2月開催です';if(typeof showToast==='function')showToast(msg);else alert(msg);return}const t=THEMES[kind]||THEMES.normal;if(typeof player==='undefined'||Number(player.coins)<t.cost){if(typeof showToast==='function')showToast('コインが足りません');return}player.coins-=t.cost;if(typeof saveData==='function')saveData();clearTimeout(revealTimer);pending={kind,reward:reward(kind)};const o=$('realGachaOverlay');if(!o)return;o.style.display='flex';showMachine(kind);machineSound(kind);revealTimer=setTimeout(()=>finish(kind),2850)}
function close(){clearTimeout(revealTimer);pending=null;const o=$('realGachaOverlay');o?.querySelector('.gxScene,.gxResult')?.remove();if(o)o.style.display='none';if(typeof updateStats==='function')updateStats()}
function ensureSeasonPanel(){const host=$('gachaTab')||document.querySelector('#gachaScreen .authBox,#gachaScreen,.gacha-panel,.gachaTab');if(!host||host.querySelector('.seasonGachaPanel'))return;const panel=document.createElement('div');panel.className='seasonGachaPanel';panel.innerHTML=`<div class="seasonGachaTitle">季節限定ガチャ</div><div class="seasonGachaGrid"><button type="button" class="seasonGachaButton summer ${active('summer')?'':'locked'}">🌊 すずしーガチャ<br><small>300コイン・6〜8月</small></button><button type="button" class="seasonGachaButton winter ${active('winter')?'':'locked'}">🔥 暖房ガチャ<br><small>300コイン・12〜2月</small></button></div><div class="seasonGachaNote">季節外でも表示されます。開催月だけ回せます。</div>`;panel.querySelector('.summer').addEventListener('click',()=>start('summer'));panel.querySelector('.winter').addEventListener('click',()=>start('winter'));host.appendChild(panel)}
function bindButtons(){window.startRealGacha=x=>start(x===true?'rare':x||'normal');window.normalGacha=()=>start('normal');window.rareGacha=()=>start('rare');window.summerGacha=()=>start('summer');window.winterGacha=()=>start('winter');window.closeRealGacha=close;document.querySelectorAll('button[onclick]').forEach(b=>{const c=b.getAttribute('onclick')||'';let kind=null;if(/normalGacha\s*\(/.test(c))kind='normal';else if(/rareGacha\s*\(/.test(c))kind='rare';if(kind){b.removeAttribute('onclick');if(!b.dataset.gachaUpgradeBound){b.addEventListener('click',()=>start(kind));b.dataset.gachaUpgradeBound='1'}}});ensureSeasonPanel()}
window.ShooGachaUpgrade={start,close,bindButtons,version:'5'};installStyle();bindButtons();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindButtons,{once:true});clearInterval(bindTimer);bindTimer=setInterval(bindButtons,1000);setTimeout(()=>clearInterval(bindTimer),20000);
})();