(()=>{
'use strict';
const VERSION='gacha-11-v2-button-fix';
const THEMES={normal:{label:'通常11連',cost:800,cls:'normal'},rare:{label:'ゴールド11連',cost:2500,cls:'gold'},summer:{label:'すずしー11連',cost:3000,cls:'summer'},winter:{label:'暖房11連',cost:3000,cls:'winter'}};
let running=false,timer=null,pending=null;
const $=id=>document.getElementById(id);
const style=document.createElement('style');
style.textContent=`
.gacha11Panel{margin:14px 0;padding:14px;border:1px solid rgba(167,139,250,.5);border-radius:16px;background:rgba(2,6,23,.88);text-align:left}.gacha11Title{text-align:center;color:#ddd6fe;font-size:19px;font-weight:1000}.gacha11Lead,.gacha11Note{text-align:center;color:#94a3b8;font-size:11px}.gacha11Grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:11px 0}.gacha11Button{min-height:64px!important;margin:0!important;touch-action:manipulation;pointer-events:auto!important}.gacha11Button.normal{background:linear-gradient(135deg,#0891b2,#2563eb)!important}.gacha11Button.gold{background:linear-gradient(135deg,#facc15,#d97706)!important;color:#1c1917!important}.gacha11Button.summer{background:linear-gradient(135deg,#22d3ee,#0369a1)!important}.gacha11Button.winter{background:linear-gradient(135deg,#fb923c,#b91c1c)!important}.gacha11Button.locked{filter:grayscale(.8);opacity:.58}
#gacha11Overlay{position:fixed;inset:0;z-index:2147483400;display:none;align-items:center;justify-content:center;background:radial-gradient(circle at 50% 34%,rgba(67,56,202,.34),rgba(2,6,23,.98) 68%);color:#fff;overflow:auto}#gacha11Overlay.open{display:flex}.g11Scene{position:relative;width:min(760px,96vw);min-height:min(680px,96dvh);display:flex;flex-direction:column;align-items:center;justify-content:center;padding:60px 12px 18px;box-sizing:border-box}.g11Header{position:absolute;top:max(14px,env(safe-area-inset-top));left:16px;right:16px;display:flex;justify-content:space-between;color:#cffafe;font:1000 11px ui-monospace,monospace}.g11Machine{position:relative;width:min(620px,92vw);height:410px;border:3px solid #67e8f9;border-radius:32px;background:linear-gradient(145deg,#1e293b,#020617);overflow:hidden;box-shadow:0 0 50px rgba(56,189,248,.42)}.g11DropZone{position:absolute;inset:58px 20px 28px;border:1px solid #334155;border-radius:24px;background:radial-gradient(circle,rgba(56,189,248,.1),rgba(2,6,23,.6));overflow:hidden}.g11Capsule{position:absolute;left:var(--x);top:-100px;width:68px;height:68px;margin-left:-34px;border-radius:50%;background:linear-gradient(#ecfeff 0 48%,#2563eb 49%);border:3px solid #fff;box-shadow:0 0 22px #38bdf8;animation:g11Drop .9s .45s cubic-bezier(.16,1.1,.3,1) forwards}.g11Capsule.legend{background:linear-gradient(#fffbd1 0 48%,#d97706 49%);box-shadow:0 0 24px #fff,0 0 52px #facc15}.g11Status{margin-top:16px;color:#e0f2fe;font:1000 17px ui-monospace,monospace}.g11Skip{position:absolute!important;right:14px;bottom:14px;width:auto!important;margin:0!important;z-index:3}.g11Result{width:min(820px,96vw);max-height:96dvh;overflow:auto;padding:40px 10px 18px;box-sizing:border-box}.g11ResultTitle{text-align:center;color:#e9d5ff;font-size:34px;font-weight:1000}.g11Cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:14px}.g11Card{position:relative;min-height:112px;padding:9px;border:1px solid #334155;border-radius:12px;background:#0f172a}.g11Card.legend{border-color:#facc15;box-shadow:0 0 16px rgba(250,204,21,.35)}.g11CardName{font-size:12px;font-weight:1000}.g11CardDesc{font-size:9px;color:#94a3b8;margin-top:5px}.g11New{position:absolute;right:6px;top:6px;background:#ef4444;border-radius:999px;padding:2px 5px;font-size:7px}.g11Close{display:block;width:min(360px,90vw)!important;margin:14px auto 0!important}@keyframes g11Drop{0%{top:-100px;opacity:0;transform:scale(.5) rotate(-180deg)}70%{top:var(--y);opacity:1;transform:scale(1.08) rotate(260deg)}100%{top:var(--y);opacity:1;transform:scale(1) rotate(360deg)}}@media(max-width:620px){.g11Capsule{width:50px;height:50px;margin-left:-25px}.g11Cards{grid-template-columns:repeat(3,1fr)}.g11Machine{height:380px}.g11DropZone{inset:52px 8px 24px}}@media(max-width:380px){.gacha11Grid{grid-template-columns:1fr}.g11Cards{grid-template-columns:repeat(2,1fr)}}
`;
document.head.appendChild(style);
function getPlayer(){try{return typeof player!=='undefined'?player:window.player||null}catch{return window.player||null}}
function notify(message,type='info'){if(typeof window.showAppNotice==='function')window.showAppNotice({title:type==='error'?'GACHA ERROR':'11 CAPSULE SYSTEM',message,type,duration:5200});else window.alert(message)}
function active(kind){const m=new Date().getMonth()+1;return kind==='summer'?(m>=6&&m<=8):(m===12||m<=2)}
function boost(p,key,value){p[key]=(Number(p[key])||0)+value}
function reward(kind,p){const r=Math.random();if(kind==='rare'){if(r<.28){boost(p,'damage',.35);return {id:'rare-attack',name:'レア攻撃コア',desc:'攻撃力 +35%',legend:false}}if(r<.52){boost(p,'maxHp',50);p.hp=p.maxHp;return {id:'gold-armor',name:'黄金装甲',desc:'最大HP +50',legend:false}}if(r<.76){boost(p,'fire',.35);return {id:'rapid-fire',name:'高速連射機構',desc:'連射力 +35%',legend:false}}if(r<.94){boost(p,'engine',.4);return {id:'gold-engine',name:'金色エンジン',desc:'エンジン +40%',legend:false}}p.coins+=1000;return {id:'legend-jackpot',name:'LEGEND JACKPOT',desc:'1000コイン獲得',legend:true}}if(kind==='summer'){if(r<.3){boost(p,'fire',.45);return {id:'cool-lizard',name:'すずしートカゲ',desc:'連射力 +45%',legend:false}}if(r<.6){boost(p,'engine',.35);return {id:'water-booster',name:'ウォーターブースター',desc:'移動性能 +35%',legend:false}}if(r<.9){boost(p,'damage',.3);return {id:'ice-missile',name:'かき氷ミサイル',desc:'攻撃力 +30%',legend:false}}boost(p,'damage',.5);boost(p,'fire',.5);return {id:'summer-dragon',name:'サマードラゴン',desc:'攻撃・連射を超強化',legend:true}}if(kind==='winter'){if(r<.3){boost(p,'maxHp',55);p.hp=p.maxHp;return {id:'heater-armor',name:'暖房装甲',desc:'最大HP +55',legend:false}}if(r<.6){boost(p,'damage',.4);return {id:'stove-cannon',name:'石油ストーブ砲',desc:'攻撃力 +40%',legend:false}}if(r<.9){boost(p,'fire',.38);return {id:'kotatsu-turret',name:'こたつタレット',desc:'連射力 +38%',legend:false}}boost(p,'damage',.55);boost(p,'maxHp',100);p.hp=p.maxHp;return {id:'sun-furnace',name:'太陽炉ヒーター',desc:'攻撃 +55%・HP +100',legend:true}}if(r<.35){boost(p,'damage',.12);return {id:'attack-chip',name:'攻撃チップ',desc:'攻撃力 +12%',legend:false}}if(r<.65){boost(p,'maxHp',15);p.hp=p.maxHp;return {id:'armor-plate',name:'装甲プレート',desc:'最大HP +15',legend:false}}if(r<.88){boost(p,'fire',.12);return {id:'fire-module',name:'連射モジュール',desc:'連射力 +12%',legend:false}}boost(p,'engine',.12);return {id:'small-engine',name:'小型エンジン',desc:'エンジン +12%',legend:false}}
function remember(item){const key='shooking2_limited_items';let list=[];try{list=JSON.parse(localStorage.getItem(key)||'[]')}catch{}const isNew=!list.some(x=>x.id===item.id);if(isNew){list.push({id:item.id,name:item.name,obtainedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(list))}return isNew}
function ensureOverlay(){let el=$('gacha11Overlay');if(!el){el=document.createElement('div');el.id='gacha11Overlay';document.body.appendChild(el)}return el}
function positions(){return [[14,8],[38,5],[62,7],[86,9],[20,38],[44,36],[68,39],[86,37],[28,69],[52,68],[76,70]]}
function showMachine(kind,results){const theme=THEMES[kind],overlay=ensureOverlay(),caps=results.map((item,i)=>{const [x,y]=positions()[i];return `<i class="g11Capsule ${item.legend?'legend':''}" style="--x:${x}%;--y:${y}%"></i>`}).join('');overlay.className='open';overlay.innerHTML=`<section class="g11Scene"><div class="g11Header"><span>${theme.label}</span><span>${theme.cost} COINS</span></div><div class="g11Machine"><div class="g11DropZone">${caps}</div><button class="g11Skip" data-g11-action="skip" type="button">SKIP</button></div><div class="g11Status">11 CAPSULES EJECTING...</div></section>`}
function showResults(kind,results){const overlay=ensureOverlay(),cards=results.map(item=>`<article class="g11Card ${item.legend?'legend':''}"><div>${item.legend?'★★★★★':'★★★'}</div><div class="g11CardName">${item.name}</div><div class="g11CardDesc">${item.desc}</div>${remember(item)?'<span class="g11New">NEW</span>':''}</article>`).join('');overlay.innerHTML=`<section class="g11Result"><div class="g11ResultTitle">11連ガチャ結果</div><div class="g11Cards">${cards}</div><button class="g11Close" data-g11-action="close" type="button">11個すべて受け取る</button></section>`}
function finish(){clearTimeout(timer);if(!pending)return;const data=pending;pending=null;if(typeof saveData==='function')saveData();if(typeof checkAchievements==='function')checkAchievements();showResults(data.kind,data.results)}
function start(kind='normal'){if(running)return;const theme=THEMES[kind]||THEMES.normal;if((kind==='summer'||kind==='winter')&&!active(kind)){notify(kind==='summer'?'夏限定11連は6〜8月開催です。':'冬限定11連は12〜2月開催です。','error');return}const p=getPlayer();if(!p){notify('プレイヤーデータを読み込めませんでした。','error');return}if(Number(p.coins)<theme.cost){notify(`コインが足りません。${theme.cost}コイン必要です。`,'error');return}running=true;p.coins-=theme.cost;const results=Array.from({length:11},()=>reward(kind,p));pending={kind,results};if(typeof saveData==='function')saveData();showMachine(kind,results);timer=setTimeout(finish,2200)}
function close(){clearTimeout(timer);pending=null;running=false;const overlay=ensureOverlay();overlay.className='';overlay.replaceChildren();if(typeof updateStats==='function')updateStats();if(typeof updateUI==='function')updateUI()}
function createPanel(){const panel=document.createElement('section');panel.id='gacha11Panel';panel.className='gacha11Panel';panel.innerHTML=`<div class="gacha11Title">11連カプセルガチャ</div><div class="gacha11Lead">10回分のコインで11個出ます。</div><div class="gacha11Grid"><button class="gacha11Button normal" data-g11-kind="normal" type="button">通常11連<br><small>800コイン</small></button><button class="gacha11Button gold" data-g11-kind="rare" type="button">ゴールド11連<br><small>2500コイン</small></button><button class="gacha11Button summer ${active('summer')?'':'locked'}" data-g11-kind="summer" type="button">すずしー11連<br><small>3000コイン</small></button><button class="gacha11Button winter ${active('winter')?'':'locked'}" data-g11-kind="winter" type="button">暖房11連<br><small>3000コイン</small></button></div><div class="gacha11Note">11個のカプセルが同時に出ます。</div>`;return panel}
function inject(){const host=document.querySelector('#gachaTab,#gacha .panel,#gachaScreen .panel,#gachaScreen,#gacha');if(!host||$('gacha11Panel'))return;const panel=createPanel();const season=host.querySelector('.seasonGachaPanel');if(season)season.insertAdjacentElement('afterend',panel);else host.appendChild(panel);window.__shookingGacha11=VERSION}
document.addEventListener('click',event=>{const kindButton=event.target.closest('[data-g11-kind]');if(kindButton){event.preventDefault();event.stopPropagation();start(kindButton.dataset.g11Kind);return}const action=event.target.closest('[data-g11-action]')?.dataset.g11Action;if(action==='skip'){event.preventDefault();finish()}else if(action==='close'){event.preventDefault();close()}},true);
function install(){inject();ensureOverlay();new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});setInterval(inject,1400);window.startGacha11=start;window.closeGacha11=close;window.ShooGacha11={start,close,version:VERSION}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();